//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.CreditoWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditoWCF.ICreditoWCF")]
    public interface ICreditoWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/Credito_ListarCondicion", ReplyAction="http://tempuri.org/ICreditoWCF/Credito_ListarCondicionResponse")]
        GS.SISGEGS.DM.gsCredito_ListarCondicionResult[] Credito_ListarCondicion(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/Credito_ListarCondicion", ReplyAction="http://tempuri.org/ICreditoWCF/Credito_ListarCondicionResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsCredito_ListarCondicionResult[]> Credito_ListarCondicionAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/ObtenerLetrasSinCanje", ReplyAction="http://tempuri.org/ICreditoWCF/ObtenerLetrasSinCanjeResponse")]
        GS.SISGEGS.DM.USP_SEL_LetrasSinCanjeV2Result[] ObtenerLetrasSinCanje(int idEmpresa, int codigoUsuario, System.Nullable<int> estado, System.DateTime FechaEmisionDesde, System.DateTime FechaEmisionHasta, int dias, string zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/ObtenerLetrasSinCanje", ReplyAction="http://tempuri.org/ICreditoWCF/ObtenerLetrasSinCanjeResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.USP_SEL_LetrasSinCanjeV2Result[]> ObtenerLetrasSinCanjeAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> estado, System.DateTime FechaEmisionDesde, System.DateTime FechaEmisionHasta, int dias, string zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/ObtenerVerificacionAprobacion2", ReplyAction="http://tempuri.org/ICreditoWCF/ObtenerVerificacionAprobacion2Response")]
        GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Response ObtenerVerificacionAprobacion2(GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/ObtenerVerificacionAprobacion2", ReplyAction="http://tempuri.org/ICreditoWCF/ObtenerVerificacionAprobacion2Response")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Response> ObtenerVerificacionAprobacion2Async(GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/Enviar_Notificacion_Aprobacion2", ReplyAction="http://tempuri.org/ICreditoWCF/Enviar_Notificacion_Aprobacion2Response")]
        void Enviar_Notificacion_Aprobacion2(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string OpPedido, decimal TotalLetrasxAceptarS, decimal TotalDeudaVencidaS, decimal TotalLetrasxAceptarN, decimal TotalDeudaVencidaN, decimal TotalLetrasxAceptarI, decimal TotalDeudaVencidaI, string UsuarioAprobacion, string comentarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/Enviar_Notificacion_Aprobacion2", ReplyAction="http://tempuri.org/ICreditoWCF/Enviar_Notificacion_Aprobacion2Response")]
        System.Threading.Tasks.Task Enviar_Notificacion_Aprobacion2Async(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string OpPedido, decimal TotalLetrasxAceptarS, decimal TotalDeudaVencidaS, decimal TotalLetrasxAceptarN, decimal TotalDeudaVencidaN, decimal TotalLetrasxAceptarI, decimal TotalDeudaVencidaI, string UsuarioAprobacion, string comentarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/RegistrarLog_AprobacionDeudaVencida", ReplyAction="http://tempuri.org/ICreditoWCF/RegistrarLog_AprobacionDeudaVencidaResponse")]
        void RegistrarLog_AprobacionDeudaVencida(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string Op, decimal TotalLetrasxAceptarSil, decimal TotalDeudaVencidaSil, decimal TotalLetrasxAceptarNeo, decimal TotalDeudaVencidaNeo, decimal TotalLetrasxAceptarIna, decimal TotalDeudaVencidaIna, string comentarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoWCF/RegistrarLog_AprobacionDeudaVencida", ReplyAction="http://tempuri.org/ICreditoWCF/RegistrarLog_AprobacionDeudaVencidaResponse")]
        System.Threading.Tasks.Task RegistrarLog_AprobacionDeudaVencidaAsync(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string Op, decimal TotalLetrasxAceptarSil, decimal TotalDeudaVencidaSil, decimal TotalLetrasxAceptarNeo, decimal TotalDeudaVencidaNeo, decimal TotalLetrasxAceptarIna, decimal TotalDeudaVencidaIna, string comentarios);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerVerificacionAprobacion2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerVerificacionAprobacion2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id_agenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public GS.SISGEGS.DM.USP_SEL_Verificacion_DeudaVencidaResult[] lstdeuda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public GS.SISGEGS.DM.USP_SEL_Verificacion_LetrasxAceptarResult[] lstletras;
        
        public ObtenerVerificacionAprobacion2Request() {
        }
        
        public ObtenerVerificacionAprobacion2Request(int idEmpresa, int codigoUsuario, string id_agenda, GS.SISGEGS.DM.USP_SEL_Verificacion_DeudaVencidaResult[] lstdeuda, GS.SISGEGS.DM.USP_SEL_Verificacion_LetrasxAceptarResult[] lstletras) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.id_agenda = id_agenda;
            this.lstdeuda = lstdeuda;
            this.lstletras = lstletras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerVerificacionAprobacion2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerVerificacionAprobacion2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.USP_SEL_Verificacion_DeudaVencidaResult[] lstdeuda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GS.SISGEGS.DM.USP_SEL_Verificacion_LetrasxAceptarResult[] lstletras;
        
        public ObtenerVerificacionAprobacion2Response() {
        }
        
        public ObtenerVerificacionAprobacion2Response(GS.SISGEGS.DM.USP_SEL_Verificacion_DeudaVencidaResult[] lstdeuda, GS.SISGEGS.DM.USP_SEL_Verificacion_LetrasxAceptarResult[] lstletras) {
            this.lstdeuda = lstdeuda;
            this.lstletras = lstletras;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditoWCFChannel : GS.SISGEGS.Web.CreditoWCF.ICreditoWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditoWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.CreditoWCF.ICreditoWCF>, GS.SISGEGS.Web.CreditoWCF.ICreditoWCF {
        
        public CreditoWCFClient() {
        }
        
        public CreditoWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditoWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.gsCredito_ListarCondicionResult[] Credito_ListarCondicion(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.Credito_ListarCondicion(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsCredito_ListarCondicionResult[]> Credito_ListarCondicionAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.Credito_ListarCondicionAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.USP_SEL_LetrasSinCanjeV2Result[] ObtenerLetrasSinCanje(int idEmpresa, int codigoUsuario, System.Nullable<int> estado, System.DateTime FechaEmisionDesde, System.DateTime FechaEmisionHasta, int dias, string zona) {
            return base.Channel.ObtenerLetrasSinCanje(idEmpresa, codigoUsuario, estado, FechaEmisionDesde, FechaEmisionHasta, dias, zona);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.USP_SEL_LetrasSinCanjeV2Result[]> ObtenerLetrasSinCanjeAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> estado, System.DateTime FechaEmisionDesde, System.DateTime FechaEmisionHasta, int dias, string zona) {
            return base.Channel.ObtenerLetrasSinCanjeAsync(idEmpresa, codigoUsuario, estado, FechaEmisionDesde, FechaEmisionHasta, dias, zona);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Response GS.SISGEGS.Web.CreditoWCF.ICreditoWCF.ObtenerVerificacionAprobacion2(GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Request request) {
            return base.Channel.ObtenerVerificacionAprobacion2(request);
        }
        
        public void ObtenerVerificacionAprobacion2(int idEmpresa, int codigoUsuario, string id_agenda, ref GS.SISGEGS.DM.USP_SEL_Verificacion_DeudaVencidaResult[] lstdeuda, ref GS.SISGEGS.DM.USP_SEL_Verificacion_LetrasxAceptarResult[] lstletras) {
            GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Request inValue = new GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Request();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.id_agenda = id_agenda;
            inValue.lstdeuda = lstdeuda;
            inValue.lstletras = lstletras;
            GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Response retVal = ((GS.SISGEGS.Web.CreditoWCF.ICreditoWCF)(this)).ObtenerVerificacionAprobacion2(inValue);
            lstdeuda = retVal.lstdeuda;
            lstletras = retVal.lstletras;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Response> ObtenerVerificacionAprobacion2Async(GS.SISGEGS.Web.CreditoWCF.ObtenerVerificacionAprobacion2Request request) {
            return base.Channel.ObtenerVerificacionAprobacion2Async(request);
        }
        
        public void Enviar_Notificacion_Aprobacion2(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string OpPedido, decimal TotalLetrasxAceptarS, decimal TotalDeudaVencidaS, decimal TotalLetrasxAceptarN, decimal TotalDeudaVencidaN, decimal TotalLetrasxAceptarI, decimal TotalDeudaVencidaI, string UsuarioAprobacion, string comentarios) {
            base.Channel.Enviar_Notificacion_Aprobacion2(idEmpresa, codigoUsuario, id_agenda, NombreAgenda, OpPedido, TotalLetrasxAceptarS, TotalDeudaVencidaS, TotalLetrasxAceptarN, TotalDeudaVencidaN, TotalLetrasxAceptarI, TotalDeudaVencidaI, UsuarioAprobacion, comentarios);
        }
        
        public System.Threading.Tasks.Task Enviar_Notificacion_Aprobacion2Async(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string OpPedido, decimal TotalLetrasxAceptarS, decimal TotalDeudaVencidaS, decimal TotalLetrasxAceptarN, decimal TotalDeudaVencidaN, decimal TotalLetrasxAceptarI, decimal TotalDeudaVencidaI, string UsuarioAprobacion, string comentarios) {
            return base.Channel.Enviar_Notificacion_Aprobacion2Async(idEmpresa, codigoUsuario, id_agenda, NombreAgenda, OpPedido, TotalLetrasxAceptarS, TotalDeudaVencidaS, TotalLetrasxAceptarN, TotalDeudaVencidaN, TotalLetrasxAceptarI, TotalDeudaVencidaI, UsuarioAprobacion, comentarios);
        }
        
        public void RegistrarLog_AprobacionDeudaVencida(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string Op, decimal TotalLetrasxAceptarSil, decimal TotalDeudaVencidaSil, decimal TotalLetrasxAceptarNeo, decimal TotalDeudaVencidaNeo, decimal TotalLetrasxAceptarIna, decimal TotalDeudaVencidaIna, string comentarios) {
            base.Channel.RegistrarLog_AprobacionDeudaVencida(idEmpresa, codigoUsuario, id_agenda, NombreAgenda, Op, TotalLetrasxAceptarSil, TotalDeudaVencidaSil, TotalLetrasxAceptarNeo, TotalDeudaVencidaNeo, TotalLetrasxAceptarIna, TotalDeudaVencidaIna, comentarios);
        }
        
        public System.Threading.Tasks.Task RegistrarLog_AprobacionDeudaVencidaAsync(int idEmpresa, int codigoUsuario, string id_agenda, string NombreAgenda, string Op, decimal TotalLetrasxAceptarSil, decimal TotalDeudaVencidaSil, decimal TotalLetrasxAceptarNeo, decimal TotalDeudaVencidaNeo, decimal TotalLetrasxAceptarIna, decimal TotalDeudaVencidaIna, string comentarios) {
            return base.Channel.RegistrarLog_AprobacionDeudaVencidaAsync(idEmpresa, codigoUsuario, id_agenda, NombreAgenda, Op, TotalLetrasxAceptarSil, TotalDeudaVencidaSil, TotalLetrasxAceptarNeo, TotalDeudaVencidaNeo, TotalLetrasxAceptarIna, TotalDeudaVencidaIna, comentarios);
        }
    }
}
