//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.UnidadWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnidadWCF.IUnidadWCF")]
    public interface IUnidadWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadWCF/UnidadGestion_ListarImputables", ReplyAction="http://tempuri.org/IUnidadWCF/UnidadGestion_ListarImputablesResponse")]
        GS.SISGEGS.DM.VBG02665Result[] UnidadGestion_ListarImputables(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadWCF/UnidadGestion_ListarImputables", ReplyAction="http://tempuri.org/IUnidadWCF/UnidadGestion_ListarImputablesResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02665Result[]> UnidadGestion_ListarImputablesAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadWCF/UnidadProyecto_ListarImputables", ReplyAction="http://tempuri.org/IUnidadWCF/UnidadProyecto_ListarImputablesResponse")]
        GS.SISGEGS.DM.VBG02668Result[] UnidadProyecto_ListarImputables(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadWCF/UnidadProyecto_ListarImputables", ReplyAction="http://tempuri.org/IUnidadWCF/UnidadProyecto_ListarImputablesResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02668Result[]> UnidadProyecto_ListarImputablesAsync(int idEmpresa, int codigoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnidadWCFChannel : GS.SISGEGS.Web.UnidadWCF.IUnidadWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnidadWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.UnidadWCF.IUnidadWCF>, GS.SISGEGS.Web.UnidadWCF.IUnidadWCF {
        
        public UnidadWCFClient() {
        }
        
        public UnidadWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnidadWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnidadWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnidadWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.VBG02665Result[] UnidadGestion_ListarImputables(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadGestion_ListarImputables(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02665Result[]> UnidadGestion_ListarImputablesAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadGestion_ListarImputablesAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.VBG02668Result[] UnidadProyecto_ListarImputables(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadProyecto_ListarImputables(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02668Result[]> UnidadProyecto_ListarImputablesAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadProyecto_ListarImputablesAsync(idEmpresa, codigoUsuario);
        }
    }
}
