//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.WINComision.EmpresaWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa_ComboBoxResult", Namespace="http://schemas.datacontract.org/2004/07/GS.SISGEGS.DM")]
    [System.SerializableAttribute()]
    public partial class Empresa_ComboBoxResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baseDatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoRHPlusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreComercialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baseDatos {
            get {
                return this.baseDatosField;
            }
            set {
                if ((object.ReferenceEquals(this.baseDatosField, value) != true)) {
                    this.baseDatosField = value;
                    this.RaisePropertyChanged("baseDatos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoRHPlus {
            get {
                return this.codigoRHPlusField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoRHPlusField, value) != true)) {
                    this.codigoRHPlusField = value;
                    this.RaisePropertyChanged("codigoRHPlus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreComercialField, value) != true)) {
                    this.nombreComercialField = value;
                    this.RaisePropertyChanged("nombreComercial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa_BuscarDetalleResult", Namespace="http://schemas.datacontract.org/2004/07/GS.SISGEGS.DM")]
    [System.SerializableAttribute()]
    public partial class Empresa_BuscarDetalleResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baseDatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rucField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baseDatos {
            get {
                return this.baseDatosField;
            }
            set {
                if ((object.ReferenceEquals(this.baseDatosField, value) != true)) {
                    this.baseDatosField = value;
                    this.RaisePropertyChanged("baseDatos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string logotipo {
            get {
                return this.logotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.logotipoField, value) != true)) {
                    this.logotipoField = value;
                    this.RaisePropertyChanged("logotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreComercialField, value) != true)) {
                    this.nombreComercialField = value;
                    this.RaisePropertyChanged("nombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                if ((object.ReferenceEquals(this.rucField, value) != true)) {
                    this.rucField = value;
                    this.RaisePropertyChanged("ruc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa_ListarResult", Namespace="http://schemas.datacontract.org/2004/07/GS.SISGEGS.DM")]
    [System.SerializableAttribute()]
    public partial class Empresa_ListarResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProvisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baseDatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rucField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Provision {
            get {
                return this.ProvisionField;
            }
            set {
                if ((this.ProvisionField.Equals(value) != true)) {
                    this.ProvisionField = value;
                    this.RaisePropertyChanged("Provision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baseDatos {
            get {
                return this.baseDatosField;
            }
            set {
                if ((object.ReferenceEquals(this.baseDatosField, value) != true)) {
                    this.baseDatosField = value;
                    this.RaisePropertyChanged("baseDatos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string logotipo {
            get {
                return this.logotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.logotipoField, value) != true)) {
                    this.logotipoField = value;
                    this.RaisePropertyChanged("logotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreComercialField, value) != true)) {
                    this.nombreComercialField = value;
                    this.RaisePropertyChanged("nombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                if ((object.ReferenceEquals(this.rucField, value) != true)) {
                    this.rucField = value;
                    this.RaisePropertyChanged("ruc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpresaWCF.IEmpresaWCF")]
    public interface IEmpresaWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_ComboBox", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_ComboBoxResponse")]
        GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ComboBoxResult[] Empresa_ComboBox();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_ComboBox", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_ComboBoxResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ComboBoxResult[]> Empresa_ComboBoxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_BuscarDetalle", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_BuscarDetalleResponse")]
        GS.SISGEGS.WINComision.EmpresaWCF.Empresa_BuscarDetalleResult[] Empresa_BuscarDetalle(int idEmmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_BuscarDetalle", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_BuscarDetalleResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.WINComision.EmpresaWCF.Empresa_BuscarDetalleResult[]> Empresa_BuscarDetalleAsync(int idEmmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_Listar", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_ListarResponse")]
        GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ListarResult[] Empresa_Listar(int idEmmpresa, string detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_Listar", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ListarResult[]> Empresa_ListarAsync(int idEmmpresa, string detalle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresaWCFChannel : GS.SISGEGS.WINComision.EmpresaWCF.IEmpresaWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.WINComision.EmpresaWCF.IEmpresaWCF>, GS.SISGEGS.WINComision.EmpresaWCF.IEmpresaWCF {
        
        public EmpresaWCFClient() {
        }
        
        public EmpresaWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ComboBoxResult[] Empresa_ComboBox() {
            return base.Channel.Empresa_ComboBox();
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ComboBoxResult[]> Empresa_ComboBoxAsync() {
            return base.Channel.Empresa_ComboBoxAsync();
        }
        
        public GS.SISGEGS.WINComision.EmpresaWCF.Empresa_BuscarDetalleResult[] Empresa_BuscarDetalle(int idEmmpresa) {
            return base.Channel.Empresa_BuscarDetalle(idEmmpresa);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.WINComision.EmpresaWCF.Empresa_BuscarDetalleResult[]> Empresa_BuscarDetalleAsync(int idEmmpresa) {
            return base.Channel.Empresa_BuscarDetalleAsync(idEmmpresa);
        }
        
        public GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ListarResult[] Empresa_Listar(int idEmmpresa, string detalle) {
            return base.Channel.Empresa_Listar(idEmmpresa, detalle);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.WINComision.EmpresaWCF.Empresa_ListarResult[]> Empresa_ListarAsync(int idEmmpresa, string detalle) {
            return base.Channel.Empresa_ListarAsync(idEmmpresa, detalle);
        }
    }
}
