//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.MonedaWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonedaWCF.IMonedaWCF")]
    public interface IMonedaWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonedaWCF/Moneda_Listar", ReplyAction="http://tempuri.org/IMonedaWCF/Moneda_ListarResponse")]
        GS.SISGEGS.DM.VBG00187Result[] Moneda_Listar(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonedaWCF/Moneda_Listar", ReplyAction="http://tempuri.org/IMonedaWCF/Moneda_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00187Result[]> Moneda_ListarAsync(int idEmpresa, int codigoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonedaWCFChannel : GS.SISGEGS.Web.MonedaWCF.IMonedaWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonedaWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.MonedaWCF.IMonedaWCF>, GS.SISGEGS.Web.MonedaWCF.IMonedaWCF {
        
        public MonedaWCFClient() {
        }
        
        public MonedaWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonedaWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonedaWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonedaWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.VBG00187Result[] Moneda_Listar(int idEmpresa, int codigoUsuario) {
            return base.Channel.Moneda_Listar(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00187Result[]> Moneda_ListarAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Moneda_ListarAsync(idEmpresa, codigoUsuario);
        }
    }
}
