//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.EgresosWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EgresosWCF.IEgresosWCF")]
    public interface IEgresosWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_ListarCajaChica", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_ListarCajaChicaResponse")]
        GS.SISGEGS.DM.gsEgresosVarios_ListarCajaChicaResult[] EgresosVarios_ListarCajaChica(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor, string serie, decimal numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_ListarCajaChica", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_ListarCajaChicaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVarios_ListarCajaChicaResult[]> EgresosVarios_ListarCajaChicaAsync(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor, string serie, decimal numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Buscar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_BuscarResponse")]
        GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarResponse EgresosVarios_Buscar(GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Buscar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_BuscarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarResponse> EgresosVarios_BuscarAsync(GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Registrar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_RegistrarResponse")]
        void EgresosVarios_Registrar(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Registrar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_RegistrarResponse")]
        System.Threading.Tasks.Task EgresosVarios_RegistrarAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Eliminar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_EliminarResponse")]
        void EgresosVarios_Eliminar(int idEmpresa, int codigoUsuario, int idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Eliminar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_EliminarResponse")]
        System.Threading.Tasks.Task EgresosVarios_EliminarAsync(int idEmpresa, int codigoUsuario, int idOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosUsuario_Buscar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosUsuario_BuscarResponse")]
        GS.SISGEGS.DM.gsEgresosVariosUsuario_BuscarResult EgresosVariosUsuario_Buscar(int idEmpresa, int codigoUsuario, string ID_Agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosUsuario_Buscar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosUsuario_BuscarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVariosUsuario_BuscarResult> EgresosVariosUsuario_BuscarAsync(int idEmpresa, int codigoUsuario, string ID_Agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosAprobar_Registrar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosAprobar_RegistrarResponse")]
        void EgresosVariosAprobar_Registrar(int idEmpresa, int codigoUsuario, int Op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosAprobar_Registrar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosAprobar_RegistrarResponse")]
        System.Threading.Tasks.Task EgresosVariosAprobar_RegistrarAsync(int idEmpresa, int codigoUsuario, int Op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Aprobar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_AprobarResponse")]
        void EgresosVarios_Aprobar(int idEmpresa, int codigoUsuario, decimal ID_Doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_Aprobar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_AprobarResponse")]
        System.Threading.Tasks.Task EgresosVarios_AprobarAsync(int idEmpresa, int codigoUsuario, decimal ID_Doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/NaturalezaGasto_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/NaturalezaGasto_ListarImputablesResponse")]
        GS.SISGEGS.DM.VBG03096Result[] NaturalezaGasto_ListarImputables(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/NaturalezaGasto_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/NaturalezaGasto_ListarImputablesResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG03096Result[]> NaturalezaGasto_ListarImputablesAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/UnidadGestion_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/UnidadGestion_ListarImputablesResponse")]
        GS.SISGEGS.DM.VBG02665Result[] UnidadGestion_ListarImputables(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/UnidadGestion_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/UnidadGestion_ListarImputablesResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02665Result[]> UnidadGestion_ListarImputablesAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/UnidadProyecto_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/UnidadProyecto_ListarImputablesResponse")]
        GS.SISGEGS.DM.VBG02668Result[] UnidadProyecto_ListarImputables(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/UnidadProyecto_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/UnidadProyecto_ListarImputablesResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02668Result[]> UnidadProyecto_ListarImputablesAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/CentroCosto_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/CentroCosto_ListarImputablesResponse")]
        GS.SISGEGS.DM.VBG00786Result[] CentroCosto_ListarImputables(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/CentroCosto_ListarImputables", ReplyAction="http://tempuri.org/IEgresosWCF/CentroCosto_ListarImputablesResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00786Result[]> CentroCosto_ListarImputablesAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/Documento_ListarDocCompra", ReplyAction="http://tempuri.org/IEgresosWCF/Documento_ListarDocCompraResponse")]
        GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[] Documento_ListarDocCompra(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/Documento_ListarDocCompra", ReplyAction="http://tempuri.org/IEgresosWCF/Documento_ListarDocCompraResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[]> Documento_ListarDocCompraAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/Documento_ListarEgresosVarios", ReplyAction="http://tempuri.org/IEgresosWCF/Documento_ListarEgresosVariosResponse")]
        GS.SISGEGS.DM.VBG01122Result[] Documento_ListarEgresosVarios(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/Documento_ListarEgresosVarios", ReplyAction="http://tempuri.org/IEgresosWCF/Documento_ListarEgresosVariosResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG01122Result[]> Documento_ListarEgresosVariosAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/RegistrarEgresosVarios", ReplyAction="http://tempuri.org/IEgresosWCF/RegistrarEgresosVariosResponse")]
        int RegistrarEgresosVarios(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVariosInt_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/RegistrarEgresosVarios", ReplyAction="http://tempuri.org/IEgresosWCF/RegistrarEgresosVariosResponse")]
        System.Threading.Tasks.Task<int> RegistrarEgresosVariosAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVariosInt_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosInt_ListarCajaChica", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosInt_ListarCajaChicaResponse")]
        GS.SISGEGS.DM.gsEgresosVariosInt_ListarCajaChicaResult[] EgresosVariosInt_ListarCajaChica(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosInt_ListarCajaChica", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosInt_ListarCajaChicaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVariosInt_ListarCajaChicaResult[]> EgresosVariosInt_ListarCajaChicaAsync(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosInt_Buscar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosInt_BuscarResponse")]
        GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarResponse EgresosVariosInt_Buscar(GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosInt_Buscar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosInt_BuscarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarResponse> EgresosVariosInt_BuscarAsync(GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/FlujoPermisoEditar", ReplyAction="http://tempuri.org/IEgresosWCF/FlujoPermisoEditarResponse")]
        GS.SISGEGS.DM.gsFlujoPermisoEditarResult FlujoPermisoEditar(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/FlujoPermisoEditar", ReplyAction="http://tempuri.org/IEgresosWCF/FlujoPermisoEditarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsFlujoPermisoEditarResult> FlujoPermisoEditarAsync(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/AprobarEgresoVariosFlujo", ReplyAction="http://tempuri.org/IEgresosWCF/AprobarEgresoVariosFlujoResponse")]
        void AprobarEgresoVariosFlujo(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto, int Id, char Ok, string Observacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/AprobarEgresoVariosFlujo", ReplyAction="http://tempuri.org/IEgresosWCF/AprobarEgresoVariosFlujoResponse")]
        System.Threading.Tasks.Task AprobarEgresoVariosFlujoAsync(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto, int Id, char Ok, string Observacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresoCajaFlujo", ReplyAction="http://tempuri.org/IEgresosWCF/EgresoCajaFlujoResponse")]
        GS.SISGEGS.DM.gsEgresoCajaFlujoResult[] EgresoCajaFlujo(int idEmpresa, int codigoUsuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresoCajaFlujo", ReplyAction="http://tempuri.org/IEgresosWCF/EgresoCajaFlujoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresoCajaFlujoResult[]> EgresoCajaFlujoAsync(int idEmpresa, int codigoUsuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosInt_Eliminar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosInt_EliminarResponse")]
        void EgresosVariosInt_Eliminar(int idEmpresa, int codigoUsuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosInt_Eliminar", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosInt_EliminarResponse")]
        System.Threading.Tasks.Task EgresosVariosInt_EliminarAsync(int idEmpresa, int codigoUsuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/IndicadorEnvio", ReplyAction="http://tempuri.org/IEgresosWCF/IndicadorEnvioResponse")]
        GS.SISGEGS.DM.gsIndicadorEnvioResult[] IndicadorEnvio(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/IndicadorEnvio", ReplyAction="http://tempuri.org/IEgresosWCF/IndicadorEnvioResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsIndicadorEnvioResult[]> IndicadorEnvioAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_RegistrarGenesys", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_RegistrarGenesysResponse")]
        void EgresosVarios_RegistrarGenesys(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVarios_RegistrarGenesys", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVarios_RegistrarGenesysResponse")]
        System.Threading.Tasks.Task EgresosVarios_RegistrarGenesysAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosFechaInicio_Obtener", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosFechaInicio_ObtenerResponse")]
        System.DateTime EgresosVariosFechaInicio_Obtener(int idEmpresa, int codigoUsuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/EgresosVariosFechaInicio_Obtener", ReplyAction="http://tempuri.org/IEgresosWCF/EgresosVariosFechaInicio_ObtenerResponse")]
        System.Threading.Tasks.Task<System.DateTime> EgresosVariosFechaInicio_ObtenerAsync(int idEmpresa, int codigoUsuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/ListarObservaciones_Usuario", ReplyAction="http://tempuri.org/IEgresosWCF/ListarObservaciones_UsuarioResponse")]
        GS.SISGEGS.DM.gsEgresosVarios_MaxObservacionesResult[] ListarObservaciones_Usuario(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/ListarObservaciones_Usuario", ReplyAction="http://tempuri.org/IEgresosWCF/ListarObservaciones_UsuarioResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVarios_MaxObservacionesResult[]> ListarObservaciones_UsuarioAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/ListarDetalleObservaciones_Usuario", ReplyAction="http://tempuri.org/IEgresosWCF/ListarDetalleObservaciones_UsuarioResponse")]
        GS.SISGEGS.DM.gsEgresosVarios_DetalleObservacionesResult[] ListarDetalleObservaciones_Usuario(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/ListarDetalleObservaciones_Usuario", ReplyAction="http://tempuri.org/IEgresosWCF/ListarDetalleObservaciones_UsuarioResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVarios_DetalleObservacionesResult[]> ListarDetalleObservaciones_UsuarioAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/ListarIndicadorNoEnvio", ReplyAction="http://tempuri.org/IEgresosWCF/ListarIndicadorNoEnvioResponse")]
        GS.SISGEGS.DM.gsIndicadorNoEnvioResult[] ListarIndicadorNoEnvio(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEgresosWCF/ListarIndicadorNoEnvio", ReplyAction="http://tempuri.org/IEgresosWCF/ListarIndicadorNoEnvioResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsIndicadorNoEnvioResult[]> ListarIndicadorNoEnvioAsync(int idEmpresa, int codigoUsuario);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EgresosVarios_Buscar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EgresosVarios_BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int idOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<bool> bloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string mensajeBloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEgresosVarios;
        
        public EgresosVarios_BuscarRequest() {
        }
        
        public EgresosVarios_BuscarRequest(int idEmpresa, int codigoUsuario, int idOperacion, System.Nullable<bool> bloqueado, string mensajeBloqueado, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEgresosVarios) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idOperacion = idOperacion;
            this.bloqueado = bloqueado;
            this.mensajeBloqueado = mensajeBloqueado;
            this.lstEgresosVarios = lstEgresosVarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EgresosVarios_BuscarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EgresosVarios_BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult EgresosVarios_BuscarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<bool> bloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeBloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEgresosVarios;
        
        public EgresosVarios_BuscarResponse() {
        }
        
        public EgresosVarios_BuscarResponse(GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult EgresosVarios_BuscarResult, System.Nullable<bool> bloqueado, string mensajeBloqueado, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEgresosVarios) {
            this.EgresosVarios_BuscarResult = EgresosVarios_BuscarResult;
            this.bloqueado = bloqueado;
            this.mensajeBloqueado = mensajeBloqueado;
            this.lstEgresosVarios = lstEgresosVarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EgresosVariosInt_Buscar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EgresosVariosInt_BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int idOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<bool> bloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string mensajeBloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEgresosVarios;
        
        public EgresosVariosInt_BuscarRequest() {
        }
        
        public EgresosVariosInt_BuscarRequest(int idEmpresa, int codigoUsuario, int idOperacion, System.Nullable<bool> bloqueado, string mensajeBloqueado, GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEgresosVarios) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idOperacion = idOperacion;
            this.bloqueado = bloqueado;
            this.mensajeBloqueado = mensajeBloqueado;
            this.lstEgresosVarios = lstEgresosVarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EgresosVariosInt_BuscarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EgresosVariosInt_BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.gsEgresosVariosInt_BuscarCabeceraResult EgresosVariosInt_BuscarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<bool> bloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeBloqueado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEgresosVarios;
        
        public EgresosVariosInt_BuscarResponse() {
        }
        
        public EgresosVariosInt_BuscarResponse(GS.SISGEGS.DM.gsEgresosVariosInt_BuscarCabeceraResult EgresosVariosInt_BuscarResult, System.Nullable<bool> bloqueado, string mensajeBloqueado, GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEgresosVarios) {
            this.EgresosVariosInt_BuscarResult = EgresosVariosInt_BuscarResult;
            this.bloqueado = bloqueado;
            this.mensajeBloqueado = mensajeBloqueado;
            this.lstEgresosVarios = lstEgresosVarios;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEgresosWCFChannel : GS.SISGEGS.Web.EgresosWCF.IEgresosWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EgresosWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.EgresosWCF.IEgresosWCF>, GS.SISGEGS.Web.EgresosWCF.IEgresosWCF {
        
        public EgresosWCFClient() {
        }
        
        public EgresosWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EgresosWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EgresosWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EgresosWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.gsEgresosVarios_ListarCajaChicaResult[] EgresosVarios_ListarCajaChica(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor, string serie, decimal numero) {
            return base.Channel.EgresosVarios_ListarCajaChica(idEmpresa, codigoUsuario, idAgenda, fechaInicio, fechaFinal, revisarGastos, id_proveedor, serie, numero);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVarios_ListarCajaChicaResult[]> EgresosVarios_ListarCajaChicaAsync(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor, string serie, decimal numero) {
            return base.Channel.EgresosVarios_ListarCajaChicaAsync(idEmpresa, codigoUsuario, idAgenda, fechaInicio, fechaFinal, revisarGastos, id_proveedor, serie, numero);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarResponse GS.SISGEGS.Web.EgresosWCF.IEgresosWCF.EgresosVarios_Buscar(GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarRequest request) {
            return base.Channel.EgresosVarios_Buscar(request);
        }
        
        public GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult EgresosVarios_Buscar(int idEmpresa, int codigoUsuario, int idOperacion, ref System.Nullable<bool> bloqueado, ref string mensajeBloqueado, ref GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEgresosVarios) {
            GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarRequest inValue = new GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idOperacion = idOperacion;
            inValue.bloqueado = bloqueado;
            inValue.mensajeBloqueado = mensajeBloqueado;
            inValue.lstEgresosVarios = lstEgresosVarios;
            GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarResponse retVal = ((GS.SISGEGS.Web.EgresosWCF.IEgresosWCF)(this)).EgresosVarios_Buscar(inValue);
            bloqueado = retVal.bloqueado;
            mensajeBloqueado = retVal.mensajeBloqueado;
            lstEgresosVarios = retVal.lstEgresosVarios;
            return retVal.EgresosVarios_BuscarResult;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarResponse> EgresosVarios_BuscarAsync(GS.SISGEGS.Web.EgresosWCF.EgresosVarios_BuscarRequest request) {
            return base.Channel.EgresosVarios_BuscarAsync(request);
        }
        
        public void EgresosVarios_Registrar(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio) {
            base.Channel.EgresosVarios_Registrar(idEmpresa, codigoUsuario, objEVCabecera, lstEVDetalles, fechaInicio);
        }
        
        public System.Threading.Tasks.Task EgresosVarios_RegistrarAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio) {
            return base.Channel.EgresosVarios_RegistrarAsync(idEmpresa, codigoUsuario, objEVCabecera, lstEVDetalles, fechaInicio);
        }
        
        public void EgresosVarios_Eliminar(int idEmpresa, int codigoUsuario, int idOperacion) {
            base.Channel.EgresosVarios_Eliminar(idEmpresa, codigoUsuario, idOperacion);
        }
        
        public System.Threading.Tasks.Task EgresosVarios_EliminarAsync(int idEmpresa, int codigoUsuario, int idOperacion) {
            return base.Channel.EgresosVarios_EliminarAsync(idEmpresa, codigoUsuario, idOperacion);
        }
        
        public GS.SISGEGS.DM.gsEgresosVariosUsuario_BuscarResult EgresosVariosUsuario_Buscar(int idEmpresa, int codigoUsuario, string ID_Agenda) {
            return base.Channel.EgresosVariosUsuario_Buscar(idEmpresa, codigoUsuario, ID_Agenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVariosUsuario_BuscarResult> EgresosVariosUsuario_BuscarAsync(int idEmpresa, int codigoUsuario, string ID_Agenda) {
            return base.Channel.EgresosVariosUsuario_BuscarAsync(idEmpresa, codigoUsuario, ID_Agenda);
        }
        
        public void EgresosVariosAprobar_Registrar(int idEmpresa, int codigoUsuario, int Op) {
            base.Channel.EgresosVariosAprobar_Registrar(idEmpresa, codigoUsuario, Op);
        }
        
        public System.Threading.Tasks.Task EgresosVariosAprobar_RegistrarAsync(int idEmpresa, int codigoUsuario, int Op) {
            return base.Channel.EgresosVariosAprobar_RegistrarAsync(idEmpresa, codigoUsuario, Op);
        }
        
        public void EgresosVarios_Aprobar(int idEmpresa, int codigoUsuario, decimal ID_Doc) {
            base.Channel.EgresosVarios_Aprobar(idEmpresa, codigoUsuario, ID_Doc);
        }
        
        public System.Threading.Tasks.Task EgresosVarios_AprobarAsync(int idEmpresa, int codigoUsuario, decimal ID_Doc) {
            return base.Channel.EgresosVarios_AprobarAsync(idEmpresa, codigoUsuario, ID_Doc);
        }
        
        public GS.SISGEGS.DM.VBG03096Result[] NaturalezaGasto_ListarImputables(int idEmpresa, int codigoUsuario) {
            return base.Channel.NaturalezaGasto_ListarImputables(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG03096Result[]> NaturalezaGasto_ListarImputablesAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.NaturalezaGasto_ListarImputablesAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.VBG02665Result[] UnidadGestion_ListarImputables(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadGestion_ListarImputables(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02665Result[]> UnidadGestion_ListarImputablesAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadGestion_ListarImputablesAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.VBG02668Result[] UnidadProyecto_ListarImputables(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadProyecto_ListarImputables(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02668Result[]> UnidadProyecto_ListarImputablesAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.UnidadProyecto_ListarImputablesAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.VBG00786Result[] CentroCosto_ListarImputables(int idEmpresa, int codigoUsuario) {
            return base.Channel.CentroCosto_ListarImputables(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00786Result[]> CentroCosto_ListarImputablesAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.CentroCosto_ListarImputablesAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[] Documento_ListarDocCompra(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarDocCompra(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[]> Documento_ListarDocCompraAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarDocCompraAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.VBG01122Result[] Documento_ListarEgresosVarios(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarEgresosVarios(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG01122Result[]> Documento_ListarEgresosVariosAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarEgresosVariosAsync(idEmpresa, codigoUsuario);
        }
        
        public int RegistrarEgresosVarios(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVariosInt_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio) {
            return base.Channel.RegistrarEgresosVarios(idEmpresa, codigoUsuario, objEVCabecera, lstEVDetalles, fechaInicio);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarEgresosVariosAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVariosInt_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio) {
            return base.Channel.RegistrarEgresosVariosAsync(idEmpresa, codigoUsuario, objEVCabecera, lstEVDetalles, fechaInicio);
        }
        
        public GS.SISGEGS.DM.gsEgresosVariosInt_ListarCajaChicaResult[] EgresosVariosInt_ListarCajaChica(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor) {
            return base.Channel.EgresosVariosInt_ListarCajaChica(idEmpresa, codigoUsuario, idAgenda, fechaInicio, fechaFinal, revisarGastos, id_proveedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVariosInt_ListarCajaChicaResult[]> EgresosVariosInt_ListarCajaChicaAsync(int idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, bool revisarGastos, string id_proveedor) {
            return base.Channel.EgresosVariosInt_ListarCajaChicaAsync(idEmpresa, codigoUsuario, idAgenda, fechaInicio, fechaFinal, revisarGastos, id_proveedor);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarResponse GS.SISGEGS.Web.EgresosWCF.IEgresosWCF.EgresosVariosInt_Buscar(GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarRequest request) {
            return base.Channel.EgresosVariosInt_Buscar(request);
        }
        
        public GS.SISGEGS.DM.gsEgresosVariosInt_BuscarCabeceraResult EgresosVariosInt_Buscar(int idEmpresa, int codigoUsuario, int idOperacion, ref System.Nullable<bool> bloqueado, ref string mensajeBloqueado, ref GS.SISGEGS.DM.gsEgresosVariosDInt_BuscarDetalleResult[] lstEgresosVarios) {
            GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarRequest inValue = new GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idOperacion = idOperacion;
            inValue.bloqueado = bloqueado;
            inValue.mensajeBloqueado = mensajeBloqueado;
            inValue.lstEgresosVarios = lstEgresosVarios;
            GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarResponse retVal = ((GS.SISGEGS.Web.EgresosWCF.IEgresosWCF)(this)).EgresosVariosInt_Buscar(inValue);
            bloqueado = retVal.bloqueado;
            mensajeBloqueado = retVal.mensajeBloqueado;
            lstEgresosVarios = retVal.lstEgresosVarios;
            return retVal.EgresosVariosInt_BuscarResult;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarResponse> EgresosVariosInt_BuscarAsync(GS.SISGEGS.Web.EgresosWCF.EgresosVariosInt_BuscarRequest request) {
            return base.Channel.EgresosVariosInt_BuscarAsync(request);
        }
        
        public GS.SISGEGS.DM.gsFlujoPermisoEditarResult FlujoPermisoEditar(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto) {
            return base.Channel.FlujoPermisoEditar(idEmpresa, codigoUsuario, idPerfil, idCcosto);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsFlujoPermisoEditarResult> FlujoPermisoEditarAsync(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto) {
            return base.Channel.FlujoPermisoEditarAsync(idEmpresa, codigoUsuario, idPerfil, idCcosto);
        }
        
        public void AprobarEgresoVariosFlujo(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto, int Id, char Ok, string Observacion) {
            base.Channel.AprobarEgresoVariosFlujo(idEmpresa, codigoUsuario, idPerfil, idCcosto, Id, Ok, Observacion);
        }
        
        public System.Threading.Tasks.Task AprobarEgresoVariosFlujoAsync(int idEmpresa, int codigoUsuario, int idPerfil, string idCcosto, int Id, char Ok, string Observacion) {
            return base.Channel.AprobarEgresoVariosFlujoAsync(idEmpresa, codigoUsuario, idPerfil, idCcosto, Id, Ok, Observacion);
        }
        
        public GS.SISGEGS.DM.gsEgresoCajaFlujoResult[] EgresoCajaFlujo(int idEmpresa, int codigoUsuario, int id) {
            return base.Channel.EgresoCajaFlujo(idEmpresa, codigoUsuario, id);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresoCajaFlujoResult[]> EgresoCajaFlujoAsync(int idEmpresa, int codigoUsuario, int id) {
            return base.Channel.EgresoCajaFlujoAsync(idEmpresa, codigoUsuario, id);
        }
        
        public void EgresosVariosInt_Eliminar(int idEmpresa, int codigoUsuario, int id) {
            base.Channel.EgresosVariosInt_Eliminar(idEmpresa, codigoUsuario, id);
        }
        
        public System.Threading.Tasks.Task EgresosVariosInt_EliminarAsync(int idEmpresa, int codigoUsuario, int id) {
            return base.Channel.EgresosVariosInt_EliminarAsync(idEmpresa, codigoUsuario, id);
        }
        
        public GS.SISGEGS.DM.gsIndicadorEnvioResult[] IndicadorEnvio(int idEmpresa, int codigoUsuario) {
            return base.Channel.IndicadorEnvio(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsIndicadorEnvioResult[]> IndicadorEnvioAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.IndicadorEnvioAsync(idEmpresa, codigoUsuario);
        }
        
        public void EgresosVarios_RegistrarGenesys(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio, int id) {
            base.Channel.EgresosVarios_RegistrarGenesys(idEmpresa, codigoUsuario, objEVCabecera, lstEVDetalles, fechaInicio, id);
        }
        
        public System.Threading.Tasks.Task EgresosVarios_RegistrarGenesysAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.DM.gsEgresosVarios_BuscarCabeceraResult objEVCabecera, GS.SISGEGS.DM.gsEgresosVarios_BuscarDetalleResult[] lstEVDetalles, System.DateTime fechaInicio, int id) {
            return base.Channel.EgresosVarios_RegistrarGenesysAsync(idEmpresa, codigoUsuario, objEVCabecera, lstEVDetalles, fechaInicio, id);
        }
        
        public System.DateTime EgresosVariosFechaInicio_Obtener(int idEmpresa, int codigoUsuario, int id) {
            return base.Channel.EgresosVariosFechaInicio_Obtener(idEmpresa, codigoUsuario, id);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> EgresosVariosFechaInicio_ObtenerAsync(int idEmpresa, int codigoUsuario, int id) {
            return base.Channel.EgresosVariosFechaInicio_ObtenerAsync(idEmpresa, codigoUsuario, id);
        }
        
        public GS.SISGEGS.DM.gsEgresosVarios_MaxObservacionesResult[] ListarObservaciones_Usuario(int idEmpresa, int codigoUsuario) {
            return base.Channel.ListarObservaciones_Usuario(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVarios_MaxObservacionesResult[]> ListarObservaciones_UsuarioAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.ListarObservaciones_UsuarioAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.gsEgresosVarios_DetalleObservacionesResult[] ListarDetalleObservaciones_Usuario(int idEmpresa, int codigoUsuario) {
            return base.Channel.ListarDetalleObservaciones_Usuario(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsEgresosVarios_DetalleObservacionesResult[]> ListarDetalleObservaciones_UsuarioAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.ListarDetalleObservaciones_UsuarioAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.gsIndicadorNoEnvioResult[] ListarIndicadorNoEnvio(int idEmpresa, int codigoUsuario) {
            return base.Channel.ListarIndicadorNoEnvio(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsIndicadorNoEnvioResult[]> ListarIndicadorNoEnvioAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.ListarIndicadorNoEnvioAsync(idEmpresa, codigoUsuario);
        }
    }
}
