//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.EmpresaWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpresaWCF.IEmpresaWCF")]
    public interface IEmpresaWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_ComboBox", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_ComboBoxResponse")]
        GS.SISGEGS.DM.Empresa_ComboBoxResult[] Empresa_ComboBox();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaWCF/Empresa_ComboBox", ReplyAction="http://tempuri.org/IEmpresaWCF/Empresa_ComboBoxResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.Empresa_ComboBoxResult[]> Empresa_ComboBoxAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresaWCFChannel : GS.SISGEGS.Web.EmpresaWCF.IEmpresaWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.EmpresaWCF.IEmpresaWCF>, GS.SISGEGS.Web.EmpresaWCF.IEmpresaWCF {
        
        public EmpresaWCFClient() {
        }
        
        public EmpresaWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.Empresa_ComboBoxResult[] Empresa_ComboBox() {
            return base.Channel.Empresa_ComboBox();
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.Empresa_ComboBoxResult[]> Empresa_ComboBoxAsync() {
            return base.Channel.Empresa_ComboBoxAsync();
        }
    }
}
