//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.AgendaWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgendaWCF.IAgendaWCF")]
    public interface IAgendaWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarCliente", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarClienteResponse")]
        GS.SISGEGS.DM.gsAgenda_ListarClienteResult[] Agenda_ListarCliente(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarCliente", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarClienteResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarClienteResult[]> Agenda_ListarClienteAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedorResponse")]
        GS.SISGEGS.DM.gsAgenda_ListarVendedorResult[] Agenda_ListarVendedor(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedorResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarVendedorResult[]> Agenda_ListarVendedorAsync(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedores", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedoresResponse")]
        GS.SISGEGS.DM.gsVendedores_ListarResult[] Agenda_ListarVendedores(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedores", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedoresResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVendedores_ListarResult[]> Agenda_ListarVendedoresAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarClientes", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarClientesResponse")]
        GS.SISGEGS.DM.gsClientesXVendedor_ListarResult[] Agenda_ListarClientes(int idEmpresa, int codigoUsuario, string idVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarClientes", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarClientesResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsClientesXVendedor_ListarResult[]> Agenda_ListarClientesAsync(int idEmpresa, int codigoUsuario, string idVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarCliente", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarClienteResponse")]
        GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteResponse Agenda_BuscarCliente(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarCliente", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarClienteResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteResponse> Agenda_BuscarClienteAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarDireccionCliente", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarDireccionClienteResponse")]
        GS.SISGEGS.DM.VBG00167Result[] AgendaAnexo_ListarDireccionCliente(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarDireccionCliente", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarDireccionClienteResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00167Result[]> AgendaAnexo_ListarDireccionClienteAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacen", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacenResponse")]
        GS.SISGEGS.DM.VBG00746Result[] AgendaAnexo_ListarAlmacen(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacen", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacenResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00746Result[]> AgendaAnexo_ListarAlmacenAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacenCliente", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacenClienteResponse")]
        GS.SISGEGS.DM.VBG03678Result[] AgendaAnexo_ListarAlmacenCliente(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacenCliente", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexo_ListarAlmacenClienteResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG03678Result[]> AgendaAnexo_ListarAlmacenClienteAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexoReferencia_ListarPorSucursal", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexoReferencia_ListarPorSucursalResponse")]
        GS.SISGEGS.DM.VBG02699Result[] AgendaAnexoReferencia_ListarPorSucursal(int idEmpresa, int codigoUsuario, int idAgendaAnexo, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/AgendaAnexoReferencia_ListarPorSucursal", ReplyAction="http://tempuri.org/IAgendaWCF/AgendaAnexoReferencia_ListarPorSucursalResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02699Result[]> AgendaAnexoReferencia_ListarPorSucursalAsync(int idEmpresa, int codigoUsuario, int idAgendaAnexo, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_LineaCredito", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_LineaCreditoResponse")]
        GS.SISGEGS.BE.Agenda_LimiteCreditoBE Agenda_LineaCredito(int idEmpresa, int codigoUsuario, string idAgenda, decimal idMoneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_LineaCredito", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_LineaCreditoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.BE.Agenda_LimiteCreditoBE> Agenda_LineaCreditoAsync(int idEmpresa, int codigoUsuario, string idAgenda, decimal idMoneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarContacto", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarContactoResponse")]
        GS.SISGEGS.DM.gsAgenda_ListarContactoResult[] Agenda_ListarContacto(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarContacto", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarContactoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarContactoResult[]> Agenda_ListarContactoAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BucarProveedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BucarProveedorResponse")]
        GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorResponse Agenda_BucarProveedor(GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BucarProveedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BucarProveedorResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorResponse> Agenda_BucarProveedorAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarProveedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarProveedorResponse")]
        GS.SISGEGS.DM.gsAgenda_ListarProveedorResult[] Agenda_ListarProveedor(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarProveedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarProveedorResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarProveedorResult[]> Agenda_ListarProveedorAsync(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarTransportista", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarTransportistaResponse")]
        GS.SISGEGS.DM.gsAgenda_ListarTransportistaResult[] Agenda_ListarTransportista(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarTransportista", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarTransportistaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarTransportistaResult[]> Agenda_ListarTransportistaAsync(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_RegistrarProveedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_RegistrarProveedorResponse")]
        string Agenda_RegistrarProveedor(int idEmpresa, int codigoUsuario, string nroRUC, string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_RegistrarProveedor", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_RegistrarProveedorResponse")]
        System.Threading.Tasks.Task<string> Agenda_RegistrarProveedorAsync(int idEmpresa, int codigoUsuario, string nroRUC, string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarChofer", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarChoferResponse")]
        GS.SISGEGS.DM.gsChofer_ListarResult[] Agenda_ListarChofer(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Chofer, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarChofer", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarChoferResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsChofer_ListarResult[]> Agenda_ListarChoferAsync(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Chofer, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarPlaca", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarPlacaResponse")]
        GS.SISGEGS.DM.gsPlaca_ListarResult[] Agenda_ListarPlaca(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarPlaca", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarPlacaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPlaca_ListarResult[]> Agenda_ListarPlacaAsync(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarClienteDetalle", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarClienteDetalleResponse")]
        GS.SISGEGS.DM.gsAgenda_BuscarClienteDetalleResult[] Agenda_BuscarClienteDetalle(int idEmpresa, int codigoUsuario, string Id_Agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarClienteDetalle", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarClienteDetalleResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_BuscarClienteDetalleResult[]> Agenda_BuscarClienteDetalleAsync(int idEmpresa, int codigoUsuario, string Id_Agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarPlaca_Despacho", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarPlaca_DespachoResponse")]
        GS.SISGEGS.DM.gsPlaca_DespachoResult[] Agenda_ListarPlaca_Despacho(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion, string despacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarPlaca_Despacho", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarPlaca_DespachoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPlaca_DespachoResult[]> Agenda_ListarPlaca_DespachoAsync(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion, string despacho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarZonaSectorista", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarZonaSectoristaResponse")]
        GS.SISGEGS.DM.gsZonaSectorista_ListarResult[] Agenda_ListarZonaSectorista(int idEmpresa, int codigoUsuario, string id_sectorista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarZonaSectorista", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarZonaSectoristaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsZonaSectorista_ListarResult[]> Agenda_ListarZonaSectoristaAsync(int idEmpresa, int codigoUsuario, string id_sectorista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarEmpresa", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarEmpresaResponse")]
        GS.SISGEGS.DM.Agenda_BuscarEmpresaResult[] Agenda_BuscarEmpresa(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarEmpresa", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarEmpresaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.Agenda_BuscarEmpresaResult[]> Agenda_BuscarEmpresaAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarSectorista", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarSectoristaResponse")]
        GS.SISGEGS.DM.gsUsuario_SectoristaResult[] Agenda_ListarSectorista(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarSectorista", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarSectoristaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsUsuario_SectoristaResult[]> Agenda_ListarSectoristaAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarZona", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarZonaResponse")]
        GS.SISGEGS.DM.gsZona_ListarResult[] Agenda_ListarZona(int idEmpresa, int codigoUsuario, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarZona", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarZonaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsZona_ListarResult[]> Agenda_ListarZonaAsync(int idEmpresa, int codigoUsuario, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedorProyectado", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedorProyectadoResponse")]
        GS.SISGEGS.DM.gsVendedor_ListarResult[] Agenda_ListarVendedorProyectado(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedorProyectado", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarVendedorProyectadoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVendedor_ListarResult[]> Agenda_ListarVendedorProyectadoAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarCorreos", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarCorreosResponse")]
        GS.SISGEGS.DM.gsClientesCorreo_EnvioResult[] Agenda_ListarCorreos(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarCorreos", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarCorreosResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsClientesCorreo_EnvioResult[]> Agenda_ListarCorreosAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarGarantia", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarGarantiaResponse")]
        GS.SISGEGS.DM.gsAgenda_ListarGarantiaResult[] Agenda_ListarGarantia(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarGarantia", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarGarantiaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarGarantiaResult[]> Agenda_ListarGarantiaAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ValidarCorreo", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ValidarCorreoResponse")]
        GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoResponse Agenda_ValidarCorreo(GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ValidarCorreo", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ValidarCorreoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoResponse> Agenda_ValidarCorreoAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_RegistrarCorreo", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_RegistrarCorreoResponse")]
        GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoResponse Agenda_RegistrarCorreo(GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_RegistrarCorreo", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_RegistrarCorreoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoResponse> Agenda_RegistrarCorreoAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarCliente_Contado", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarCliente_ContadoResponse")]
        GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoResponse Agenda_BuscarCliente_Contado(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_BuscarCliente_Contado", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_BuscarCliente_ContadoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoResponse> Agenda_BuscarCliente_ContadoAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_TipoCambio", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_TipoCambioResponse")]
        GS.SISGEGS.DM.RPT00015Result Agenda_TipoCambio(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int ID_Moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_TipoCambio", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_TipoCambioResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.RPT00015Result> Agenda_TipoCambioAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int ID_Moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/ListarObservacionesAgenda", ReplyAction="http://tempuri.org/IAgendaWCF/ListarObservacionesAgendaResponse")]
        GS.SISGEGS.DM.gsListarObservacionesAgendaResult[] ListarObservacionesAgenda(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/ListarObservacionesAgenda", ReplyAction="http://tempuri.org/IAgendaWCF/ListarObservacionesAgendaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsListarObservacionesAgendaResult[]> ListarObservacionesAgendaAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/ListarLogLineaCredito", ReplyAction="http://tempuri.org/IAgendaWCF/ListarLogLineaCreditoResponse")]
        GS.SISGEGS.DM.gsListarLogLineaCreditoResult[] ListarLogLineaCredito(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/ListarLogLineaCredito", ReplyAction="http://tempuri.org/IAgendaWCF/ListarLogLineaCreditoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsListarLogLineaCreditoResult[]> ListarLogLineaCreditoAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/RecuperaCorreoAgenda", ReplyAction="http://tempuri.org/IAgendaWCF/RecuperaCorreoAgendaResponse")]
        GS.SISGEGS.DM.GS_RecuperaCorreoAgendaResult[] RecuperaCorreoAgenda(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/RecuperaCorreoAgenda", ReplyAction="http://tempuri.org/IAgendaWCF/RecuperaCorreoAgendaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.GS_RecuperaCorreoAgendaResult[]> RecuperaCorreoAgendaAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarContacto_Estado", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarContacto_EstadoResponse")]
        GS.SISGEGS.DM.gsAgenda_ContactoResult[] Agenda_ListarContacto_Estado(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarContacto_Estado", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarContacto_EstadoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ContactoResult[]> Agenda_ListarContacto_EstadoAsync(int idEmpresa, int codigoUsuario, string idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarClienteAgente", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarClienteAgenteResponse")]
        GS.SISGEGS.DM.gsAgenda_ListarClienteAgenteResult[] Agenda_ListarClienteAgente(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_ListarClienteAgente", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_ListarClienteAgenteResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarClienteAgenteResult[]> Agenda_ListarClienteAgenteAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_VendedorZonaListar", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_VendedorZonaListarResponse")]
        GS.SISGEGS.DM.gsVendedorZona_ListarResult[] Agenda_VendedorZonaListar(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaWCF/Agenda_VendedorZonaListar", ReplyAction="http://tempuri.org/IAgendaWCF/Agenda_VendedorZonaListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVendedorZona_ListarResult[]> Agenda_VendedorZonaListarAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_BuscarCliente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_BuscarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idAgenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<decimal> lineaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Nullable<System.DateTime> fechaVencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Nullable<decimal> TC;
        
        public Agenda_BuscarClienteRequest() {
        }
        
        public Agenda_BuscarClienteRequest(int idEmpresa, int codigoUsuario, string idAgenda, System.Nullable<decimal> lineaCredito, System.Nullable<System.DateTime> fechaVencimiento, System.Nullable<decimal> TC) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idAgenda = idAgenda;
            this.lineaCredito = lineaCredito;
            this.fechaVencimiento = fechaVencimiento;
            this.TC = TC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_BuscarClienteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_BuscarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.VBG01134Result Agenda_BuscarClienteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<decimal> lineaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<System.DateTime> fechaVencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<decimal> TC;
        
        public Agenda_BuscarClienteResponse() {
        }
        
        public Agenda_BuscarClienteResponse(GS.SISGEGS.DM.VBG01134Result Agenda_BuscarClienteResult, System.Nullable<decimal> lineaCredito, System.Nullable<System.DateTime> fechaVencimiento, System.Nullable<decimal> TC) {
            this.Agenda_BuscarClienteResult = Agenda_BuscarClienteResult;
            this.lineaCredito = lineaCredito;
            this.fechaVencimiento = fechaVencimiento;
            this.TC = TC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_BucarProveedor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_BucarProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idAgenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<bool> existe;
        
        public Agenda_BucarProveedorRequest() {
        }
        
        public Agenda_BucarProveedorRequest(int idEmpresa, int codigoUsuario, string idAgenda, System.Nullable<bool> existe) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idAgenda = idAgenda;
            this.existe = existe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_BucarProveedorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_BucarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.gsAgenda_BucarProveedorResult Agenda_BucarProveedorResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<bool> existe;
        
        public Agenda_BucarProveedorResponse() {
        }
        
        public Agenda_BucarProveedorResponse(GS.SISGEGS.DM.gsAgenda_BucarProveedorResult Agenda_BucarProveedorResult, System.Nullable<bool> existe) {
            this.Agenda_BucarProveedorResult = Agenda_BucarProveedorResult;
            this.existe = existe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_ValidarCorreo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_ValidarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idAgenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<bool> existeCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Nullable<bool> existeCorreo;
        
        public Agenda_ValidarCorreoRequest() {
        }
        
        public Agenda_ValidarCorreoRequest(int idEmpresa, int codigoUsuario, string idAgenda, System.Nullable<bool> existeCliente, System.Nullable<bool> existeCorreo) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idAgenda = idAgenda;
            this.existeCliente = existeCliente;
            this.existeCorreo = existeCorreo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_ValidarCorreoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_ValidarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.VBG01134_validarCorreoResult Agenda_ValidarCorreoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<bool> existeCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<bool> existeCorreo;
        
        public Agenda_ValidarCorreoResponse() {
        }
        
        public Agenda_ValidarCorreoResponse(GS.SISGEGS.DM.VBG01134_validarCorreoResult Agenda_ValidarCorreoResult, System.Nullable<bool> existeCliente, System.Nullable<bool> existeCorreo) {
            this.Agenda_ValidarCorreoResult = Agenda_ValidarCorreoResult;
            this.existeCliente = existeCliente;
            this.existeCorreo = existeCorreo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_RegistrarCorreo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_RegistrarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idAgenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Nullable<int> Correlativo;
        
        public Agenda_RegistrarCorreoRequest() {
        }
        
        public Agenda_RegistrarCorreoRequest(int idEmpresa, int codigoUsuario, string idAgenda, string Correo, System.Nullable<int> Correlativo) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idAgenda = idAgenda;
            this.Correo = Correo;
            this.Correlativo = Correlativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_RegistrarCorreoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_RegistrarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> Correlativo;
        
        public Agenda_RegistrarCorreoResponse() {
        }
        
        public Agenda_RegistrarCorreoResponse(System.Nullable<int> Correlativo) {
            this.Correlativo = Correlativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_BuscarCliente_Contado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_BuscarCliente_ContadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idAgenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<decimal> lineaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Nullable<System.DateTime> fechaVencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int idMoneda;
        
        public Agenda_BuscarCliente_ContadoRequest() {
        }
        
        public Agenda_BuscarCliente_ContadoRequest(int idEmpresa, int codigoUsuario, string idAgenda, System.Nullable<decimal> lineaCredito, System.Nullable<System.DateTime> fechaVencimiento, int idMoneda) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idAgenda = idAgenda;
            this.lineaCredito = lineaCredito;
            this.fechaVencimiento = fechaVencimiento;
            this.idMoneda = idMoneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Agenda_BuscarCliente_ContadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Agenda_BuscarCliente_ContadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.VBG01134Result Agenda_BuscarCliente_ContadoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<decimal> lineaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<System.DateTime> fechaVencimiento;
        
        public Agenda_BuscarCliente_ContadoResponse() {
        }
        
        public Agenda_BuscarCliente_ContadoResponse(GS.SISGEGS.DM.VBG01134Result Agenda_BuscarCliente_ContadoResult, System.Nullable<decimal> lineaCredito, System.Nullable<System.DateTime> fechaVencimiento) {
            this.Agenda_BuscarCliente_ContadoResult = Agenda_BuscarCliente_ContadoResult;
            this.lineaCredito = lineaCredito;
            this.fechaVencimiento = fechaVencimiento;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgendaWCFChannel : GS.SISGEGS.Web.AgendaWCF.IAgendaWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgendaWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.AgendaWCF.IAgendaWCF>, GS.SISGEGS.Web.AgendaWCF.IAgendaWCF {
        
        public AgendaWCFClient() {
        }
        
        public AgendaWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgendaWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.gsAgenda_ListarClienteResult[] Agenda_ListarCliente(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarCliente(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarClienteResult[]> Agenda_ListarClienteAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarClienteAsync(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        public GS.SISGEGS.DM.gsAgenda_ListarVendedorResult[] Agenda_ListarVendedor(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Agenda_ListarVendedor(idEmpresa, codigoUsuario, descripcion);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarVendedorResult[]> Agenda_ListarVendedorAsync(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Agenda_ListarVendedorAsync(idEmpresa, codigoUsuario, descripcion);
        }
        
        public GS.SISGEGS.DM.gsVendedores_ListarResult[] Agenda_ListarVendedores(int idEmpresa, int codigoUsuario) {
            return base.Channel.Agenda_ListarVendedores(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVendedores_ListarResult[]> Agenda_ListarVendedoresAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Agenda_ListarVendedoresAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.gsClientesXVendedor_ListarResult[] Agenda_ListarClientes(int idEmpresa, int codigoUsuario, string idVendedor) {
            return base.Channel.Agenda_ListarClientes(idEmpresa, codigoUsuario, idVendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsClientesXVendedor_ListarResult[]> Agenda_ListarClientesAsync(int idEmpresa, int codigoUsuario, string idVendedor) {
            return base.Channel.Agenda_ListarClientesAsync(idEmpresa, codigoUsuario, idVendedor);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteResponse GS.SISGEGS.Web.AgendaWCF.IAgendaWCF.Agenda_BuscarCliente(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteRequest request) {
            return base.Channel.Agenda_BuscarCliente(request);
        }
        
        public GS.SISGEGS.DM.VBG01134Result Agenda_BuscarCliente(int idEmpresa, int codigoUsuario, string idAgenda, ref System.Nullable<decimal> lineaCredito, ref System.Nullable<System.DateTime> fechaVencimiento, ref System.Nullable<decimal> TC) {
            GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteRequest inValue = new GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idAgenda = idAgenda;
            inValue.lineaCredito = lineaCredito;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.TC = TC;
            GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteResponse retVal = ((GS.SISGEGS.Web.AgendaWCF.IAgendaWCF)(this)).Agenda_BuscarCliente(inValue);
            lineaCredito = retVal.lineaCredito;
            fechaVencimiento = retVal.fechaVencimiento;
            TC = retVal.TC;
            return retVal.Agenda_BuscarClienteResult;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteResponse> Agenda_BuscarClienteAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarClienteRequest request) {
            return base.Channel.Agenda_BuscarClienteAsync(request);
        }
        
        public GS.SISGEGS.DM.VBG00167Result[] AgendaAnexo_ListarDireccionCliente(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.AgendaAnexo_ListarDireccionCliente(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00167Result[]> AgendaAnexo_ListarDireccionClienteAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.AgendaAnexo_ListarDireccionClienteAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.VBG00746Result[] AgendaAnexo_ListarAlmacen(int idEmpresa, int codigoUsuario) {
            return base.Channel.AgendaAnexo_ListarAlmacen(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00746Result[]> AgendaAnexo_ListarAlmacenAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.AgendaAnexo_ListarAlmacenAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.VBG03678Result[] AgendaAnexo_ListarAlmacenCliente(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.AgendaAnexo_ListarAlmacenCliente(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG03678Result[]> AgendaAnexo_ListarAlmacenClienteAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.AgendaAnexo_ListarAlmacenClienteAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.VBG02699Result[] AgendaAnexoReferencia_ListarPorSucursal(int idEmpresa, int codigoUsuario, int idAgendaAnexo, string idAgenda) {
            return base.Channel.AgendaAnexoReferencia_ListarPorSucursal(idEmpresa, codigoUsuario, idAgendaAnexo, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG02699Result[]> AgendaAnexoReferencia_ListarPorSucursalAsync(int idEmpresa, int codigoUsuario, int idAgendaAnexo, string idAgenda) {
            return base.Channel.AgendaAnexoReferencia_ListarPorSucursalAsync(idEmpresa, codigoUsuario, idAgendaAnexo, idAgenda);
        }
        
        public GS.SISGEGS.BE.Agenda_LimiteCreditoBE Agenda_LineaCredito(int idEmpresa, int codigoUsuario, string idAgenda, decimal idMoneda) {
            return base.Channel.Agenda_LineaCredito(idEmpresa, codigoUsuario, idAgenda, idMoneda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.BE.Agenda_LimiteCreditoBE> Agenda_LineaCreditoAsync(int idEmpresa, int codigoUsuario, string idAgenda, decimal idMoneda) {
            return base.Channel.Agenda_LineaCreditoAsync(idEmpresa, codigoUsuario, idAgenda, idMoneda);
        }
        
        public GS.SISGEGS.DM.gsAgenda_ListarContactoResult[] Agenda_ListarContacto(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarContacto(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarContactoResult[]> Agenda_ListarContactoAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarContactoAsync(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorResponse GS.SISGEGS.Web.AgendaWCF.IAgendaWCF.Agenda_BucarProveedor(GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorRequest request) {
            return base.Channel.Agenda_BucarProveedor(request);
        }
        
        public GS.SISGEGS.DM.gsAgenda_BucarProveedorResult Agenda_BucarProveedor(int idEmpresa, int codigoUsuario, string idAgenda, ref System.Nullable<bool> existe) {
            GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorRequest inValue = new GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idAgenda = idAgenda;
            inValue.existe = existe;
            GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorResponse retVal = ((GS.SISGEGS.Web.AgendaWCF.IAgendaWCF)(this)).Agenda_BucarProveedor(inValue);
            existe = retVal.existe;
            return retVal.Agenda_BucarProveedorResult;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorResponse> Agenda_BucarProveedorAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_BucarProveedorRequest request) {
            return base.Channel.Agenda_BucarProveedorAsync(request);
        }
        
        public GS.SISGEGS.DM.gsAgenda_ListarProveedorResult[] Agenda_ListarProveedor(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Agenda_ListarProveedor(idEmpresa, codigoUsuario, descripcion);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarProveedorResult[]> Agenda_ListarProveedorAsync(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Agenda_ListarProveedorAsync(idEmpresa, codigoUsuario, descripcion);
        }
        
        public GS.SISGEGS.DM.gsAgenda_ListarTransportistaResult[] Agenda_ListarTransportista(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Agenda_ListarTransportista(idEmpresa, codigoUsuario, descripcion);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarTransportistaResult[]> Agenda_ListarTransportistaAsync(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Agenda_ListarTransportistaAsync(idEmpresa, codigoUsuario, descripcion);
        }
        
        public string Agenda_RegistrarProveedor(int idEmpresa, int codigoUsuario, string nroRUC, string razonSocial) {
            return base.Channel.Agenda_RegistrarProveedor(idEmpresa, codigoUsuario, nroRUC, razonSocial);
        }
        
        public System.Threading.Tasks.Task<string> Agenda_RegistrarProveedorAsync(int idEmpresa, int codigoUsuario, string nroRUC, string razonSocial) {
            return base.Channel.Agenda_RegistrarProveedorAsync(idEmpresa, codigoUsuario, nroRUC, razonSocial);
        }
        
        public GS.SISGEGS.DM.gsChofer_ListarResult[] Agenda_ListarChofer(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Chofer, string descripcion) {
            return base.Channel.Agenda_ListarChofer(idEmpresa, codigoUsuario, Id_Transportista, Id_Chofer, descripcion);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsChofer_ListarResult[]> Agenda_ListarChoferAsync(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Chofer, string descripcion) {
            return base.Channel.Agenda_ListarChoferAsync(idEmpresa, codigoUsuario, Id_Transportista, Id_Chofer, descripcion);
        }
        
        public GS.SISGEGS.DM.gsPlaca_ListarResult[] Agenda_ListarPlaca(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion) {
            return base.Channel.Agenda_ListarPlaca(idEmpresa, codigoUsuario, Id_Transportista, Id_Vehiculo, descripcion);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPlaca_ListarResult[]> Agenda_ListarPlacaAsync(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion) {
            return base.Channel.Agenda_ListarPlacaAsync(idEmpresa, codigoUsuario, Id_Transportista, Id_Vehiculo, descripcion);
        }
        
        public GS.SISGEGS.DM.gsAgenda_BuscarClienteDetalleResult[] Agenda_BuscarClienteDetalle(int idEmpresa, int codigoUsuario, string Id_Agenda) {
            return base.Channel.Agenda_BuscarClienteDetalle(idEmpresa, codigoUsuario, Id_Agenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_BuscarClienteDetalleResult[]> Agenda_BuscarClienteDetalleAsync(int idEmpresa, int codigoUsuario, string Id_Agenda) {
            return base.Channel.Agenda_BuscarClienteDetalleAsync(idEmpresa, codigoUsuario, Id_Agenda);
        }
        
        public GS.SISGEGS.DM.gsPlaca_DespachoResult[] Agenda_ListarPlaca_Despacho(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion, string despacho) {
            return base.Channel.Agenda_ListarPlaca_Despacho(idEmpresa, codigoUsuario, Id_Transportista, Id_Vehiculo, descripcion, despacho);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPlaca_DespachoResult[]> Agenda_ListarPlaca_DespachoAsync(int idEmpresa, int codigoUsuario, string Id_Transportista, string Id_Vehiculo, string descripcion, string despacho) {
            return base.Channel.Agenda_ListarPlaca_DespachoAsync(idEmpresa, codigoUsuario, Id_Transportista, Id_Vehiculo, descripcion, despacho);
        }
        
        public GS.SISGEGS.DM.gsZonaSectorista_ListarResult[] Agenda_ListarZonaSectorista(int idEmpresa, int codigoUsuario, string id_sectorista) {
            return base.Channel.Agenda_ListarZonaSectorista(idEmpresa, codigoUsuario, id_sectorista);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsZonaSectorista_ListarResult[]> Agenda_ListarZonaSectoristaAsync(int idEmpresa, int codigoUsuario, string id_sectorista) {
            return base.Channel.Agenda_ListarZonaSectoristaAsync(idEmpresa, codigoUsuario, id_sectorista);
        }
        
        public GS.SISGEGS.DM.Agenda_BuscarEmpresaResult[] Agenda_BuscarEmpresa(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.Agenda_BuscarEmpresa(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.Agenda_BuscarEmpresaResult[]> Agenda_BuscarEmpresaAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.Agenda_BuscarEmpresaAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.gsUsuario_SectoristaResult[] Agenda_ListarSectorista(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarSectorista(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsUsuario_SectoristaResult[]> Agenda_ListarSectoristaAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarSectoristaAsync(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        public GS.SISGEGS.DM.gsZona_ListarResult[] Agenda_ListarZona(int idEmpresa, int codigoUsuario, int id_zona) {
            return base.Channel.Agenda_ListarZona(idEmpresa, codigoUsuario, id_zona);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsZona_ListarResult[]> Agenda_ListarZonaAsync(int idEmpresa, int codigoUsuario, int id_zona) {
            return base.Channel.Agenda_ListarZonaAsync(idEmpresa, codigoUsuario, id_zona);
        }
        
        public GS.SISGEGS.DM.gsVendedor_ListarResult[] Agenda_ListarVendedorProyectado(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_ListarVendedorProyectado(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVendedor_ListarResult[]> Agenda_ListarVendedorProyectadoAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_ListarVendedorProyectadoAsync(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.gsClientesCorreo_EnvioResult[] Agenda_ListarCorreos(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_ListarCorreos(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsClientesCorreo_EnvioResult[]> Agenda_ListarCorreosAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_ListarCorreosAsync(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.gsAgenda_ListarGarantiaResult[] Agenda_ListarGarantia(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_ListarGarantia(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarGarantiaResult[]> Agenda_ListarGarantiaAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_ListarGarantiaAsync(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoResponse GS.SISGEGS.Web.AgendaWCF.IAgendaWCF.Agenda_ValidarCorreo(GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoRequest request) {
            return base.Channel.Agenda_ValidarCorreo(request);
        }
        
        public GS.SISGEGS.DM.VBG01134_validarCorreoResult Agenda_ValidarCorreo(int idEmpresa, int codigoUsuario, string idAgenda, ref System.Nullable<bool> existeCliente, ref System.Nullable<bool> existeCorreo) {
            GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoRequest inValue = new GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idAgenda = idAgenda;
            inValue.existeCliente = existeCliente;
            inValue.existeCorreo = existeCorreo;
            GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoResponse retVal = ((GS.SISGEGS.Web.AgendaWCF.IAgendaWCF)(this)).Agenda_ValidarCorreo(inValue);
            existeCliente = retVal.existeCliente;
            existeCorreo = retVal.existeCorreo;
            return retVal.Agenda_ValidarCorreoResult;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoResponse> Agenda_ValidarCorreoAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_ValidarCorreoRequest request) {
            return base.Channel.Agenda_ValidarCorreoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoResponse GS.SISGEGS.Web.AgendaWCF.IAgendaWCF.Agenda_RegistrarCorreo(GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoRequest request) {
            return base.Channel.Agenda_RegistrarCorreo(request);
        }
        
        public void Agenda_RegistrarCorreo(int idEmpresa, int codigoUsuario, string idAgenda, string Correo, ref System.Nullable<int> Correlativo) {
            GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoRequest inValue = new GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idAgenda = idAgenda;
            inValue.Correo = Correo;
            inValue.Correlativo = Correlativo;
            GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoResponse retVal = ((GS.SISGEGS.Web.AgendaWCF.IAgendaWCF)(this)).Agenda_RegistrarCorreo(inValue);
            Correlativo = retVal.Correlativo;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoResponse> Agenda_RegistrarCorreoAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_RegistrarCorreoRequest request) {
            return base.Channel.Agenda_RegistrarCorreoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoResponse GS.SISGEGS.Web.AgendaWCF.IAgendaWCF.Agenda_BuscarCliente_Contado(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoRequest request) {
            return base.Channel.Agenda_BuscarCliente_Contado(request);
        }
        
        public GS.SISGEGS.DM.VBG01134Result Agenda_BuscarCliente_Contado(int idEmpresa, int codigoUsuario, string idAgenda, ref System.Nullable<decimal> lineaCredito, ref System.Nullable<System.DateTime> fechaVencimiento, int idMoneda) {
            GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoRequest inValue = new GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idAgenda = idAgenda;
            inValue.lineaCredito = lineaCredito;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.idMoneda = idMoneda;
            GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoResponse retVal = ((GS.SISGEGS.Web.AgendaWCF.IAgendaWCF)(this)).Agenda_BuscarCliente_Contado(inValue);
            lineaCredito = retVal.lineaCredito;
            fechaVencimiento = retVal.fechaVencimiento;
            return retVal.Agenda_BuscarCliente_ContadoResult;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoResponse> Agenda_BuscarCliente_ContadoAsync(GS.SISGEGS.Web.AgendaWCF.Agenda_BuscarCliente_ContadoRequest request) {
            return base.Channel.Agenda_BuscarCliente_ContadoAsync(request);
        }
        
        public GS.SISGEGS.DM.RPT00015Result Agenda_TipoCambio(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int ID_Moneda) {
            return base.Channel.Agenda_TipoCambio(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, ID_Moneda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.RPT00015Result> Agenda_TipoCambioAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int ID_Moneda) {
            return base.Channel.Agenda_TipoCambioAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, ID_Moneda);
        }
        
        public GS.SISGEGS.DM.gsListarObservacionesAgendaResult[] ListarObservacionesAgenda(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.ListarObservacionesAgenda(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsListarObservacionesAgendaResult[]> ListarObservacionesAgendaAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.ListarObservacionesAgendaAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.gsListarLogLineaCreditoResult[] ListarLogLineaCredito(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.ListarLogLineaCredito(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsListarLogLineaCreditoResult[]> ListarLogLineaCreditoAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.ListarLogLineaCreditoAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.GS_RecuperaCorreoAgendaResult[] RecuperaCorreoAgenda(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.RecuperaCorreoAgenda(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.GS_RecuperaCorreoAgendaResult[]> RecuperaCorreoAgendaAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.RecuperaCorreoAgendaAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.gsAgenda_ContactoResult[] Agenda_ListarContacto_Estado(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.Agenda_ListarContacto_Estado(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ContactoResult[]> Agenda_ListarContacto_EstadoAsync(int idEmpresa, int codigoUsuario, string idAgenda) {
            return base.Channel.Agenda_ListarContacto_EstadoAsync(idEmpresa, codigoUsuario, idAgenda);
        }
        
        public GS.SISGEGS.DM.gsAgenda_ListarClienteAgenteResult[] Agenda_ListarClienteAgente(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarClienteAgente(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsAgenda_ListarClienteAgenteResult[]> Agenda_ListarClienteAgenteAsync(int idEmpresa, int codigoUsuario, string descripcion, System.Nullable<int> estado) {
            return base.Channel.Agenda_ListarClienteAgenteAsync(idEmpresa, codigoUsuario, descripcion, estado);
        }
        
        public GS.SISGEGS.DM.gsVendedorZona_ListarResult[] Agenda_VendedorZonaListar(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_VendedorZonaListar(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVendedorZona_ListarResult[]> Agenda_VendedorZonaListarAsync(int idEmpresa, int codigoUsuario, int id_zona, string id_vendedor) {
            return base.Channel.Agenda_VendedorZonaListarAsync(idEmpresa, codigoUsuario, id_zona, id_vendedor);
        }
    }
}
