//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.DocumentoWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentoWCF.IDocumentoWCF")]
    public interface IDocumentoWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoWCF/Documento_ListarDocVenta", ReplyAction="http://tempuri.org/IDocumentoWCF/Documento_ListarDocVentaResponse")]
        GS.SISGEGS.DM.VBG00716Result[] Documento_ListarDocVenta(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoWCF/Documento_ListarDocVenta", ReplyAction="http://tempuri.org/IDocumentoWCF/Documento_ListarDocVentaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00716Result[]> Documento_ListarDocVentaAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoWCF/Documento_ListarDocCompra", ReplyAction="http://tempuri.org/IDocumentoWCF/Documento_ListarDocCompraResponse")]
        GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[] Documento_ListarDocCompra(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoWCF/Documento_ListarDocCompra", ReplyAction="http://tempuri.org/IDocumentoWCF/Documento_ListarDocCompraResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[]> Documento_ListarDocCompraAsync(int idEmpresa, int codigoUsuario, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoWCF/Documento_ListarEgresosVarios", ReplyAction="http://tempuri.org/IDocumentoWCF/Documento_ListarEgresosVariosResponse")]
        GS.SISGEGS.DM.VBG01122Result[] Documento_ListarEgresosVarios(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoWCF/Documento_ListarEgresosVarios", ReplyAction="http://tempuri.org/IDocumentoWCF/Documento_ListarEgresosVariosResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG01122Result[]> Documento_ListarEgresosVariosAsync(int idEmpresa, int codigoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentoWCFChannel : GS.SISGEGS.Web.DocumentoWCF.IDocumentoWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentoWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.DocumentoWCF.IDocumentoWCF>, GS.SISGEGS.Web.DocumentoWCF.IDocumentoWCF {
        
        public DocumentoWCFClient() {
        }
        
        public DocumentoWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentoWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.VBG00716Result[] Documento_ListarDocVenta(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarDocVenta(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG00716Result[]> Documento_ListarDocVentaAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarDocVentaAsync(idEmpresa, codigoUsuario);
        }
        
        public GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[] Documento_ListarDocCompra(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Documento_ListarDocCompra(idEmpresa, codigoUsuario, descripcion);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocumento_ListarTipoCompraResult[]> Documento_ListarDocCompraAsync(int idEmpresa, int codigoUsuario, string descripcion) {
            return base.Channel.Documento_ListarDocCompraAsync(idEmpresa, codigoUsuario, descripcion);
        }
        
        public GS.SISGEGS.DM.VBG01122Result[] Documento_ListarEgresosVarios(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarEgresosVarios(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG01122Result[]> Documento_ListarEgresosVariosAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Documento_ListarEgresosVariosAsync(idEmpresa, codigoUsuario);
        }
    }
}
