//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.PedidoWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoWCF.IPedidoWCF")]
    public interface IPedidoWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_ListarTipo", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_ListarTipoResponse")]
        GS.SISGEGS.DM.VBG03630Result[] Pedido_ListarTipo(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_ListarTipo", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_ListarTipoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG03630Result[]> Pedido_ListarTipoAsync(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_Listar", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_ListarResponse")]
        GS.SISGEGS.Web.PedidoWCF.Pedido_ListarResponse Pedido_Listar(GS.SISGEGS.Web.PedidoWCF.Pedido_ListarRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_Listar", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.Web.PedidoWCF.Pedido_ListarResponse> Pedido_ListarAsync(GS.SISGEGS.Web.PedidoWCF.Pedido_ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_Registrar", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_RegistrarResponse")]
        void Pedido_Registrar(int idEmpresa, int codigoUsuario, GS.SISGEGS.BE.PedidoCabBE objPedidoCabBE, GS.SISGEGS.BE.PedidoDetBE[] lstProductos, GS.SISGEGS.BE.GlosaBE[] lstImpuestos, System.Nullable<decimal> idOperacion, string password, decimal limiteCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_Registrar", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_RegistrarResponse")]
        System.Threading.Tasks.Task Pedido_RegistrarAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.BE.PedidoCabBE objPedidoCabBE, GS.SISGEGS.BE.PedidoDetBE[] lstProductos, GS.SISGEGS.BE.GlosaBE[] lstImpuestos, System.Nullable<decimal> idOperacion, string password, decimal limiteCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_BuscarCabecera", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_BuscarCabeceraResponse")]
        GS.SISGEGS.DM.gsPedido_BuscarCabeceraResult Pedido_BuscarCabecera(int idEmpresa, int codigoUsuario, int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_BuscarCabecera", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_BuscarCabeceraResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPedido_BuscarCabeceraResult> Pedido_BuscarCabeceraAsync(int idEmpresa, int codigoUsuario, int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_BuscarDetalle", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_BuscarDetalleResponse")]
        GS.SISGEGS.DM.gsPedido_BuscarDetalleResult[] Pedido_BuscarDetalle(int idEmpresa, int codigoUsuario, int idPedido, System.Nullable<decimal> idAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_BuscarDetalle", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_BuscarDetalleResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPedido_BuscarDetalleResult[]> Pedido_BuscarDetalleAsync(int idEmpresa, int codigoUsuario, int idPedido, System.Nullable<decimal> idAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_Eliminar", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_EliminarResponse")]
        void Pedido_Eliminar(int idEmpresa, int codigoUsuario, int idOperacion, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoWCF/Pedido_Eliminar", ReplyAction="http://tempuri.org/IPedidoWCF/Pedido_EliminarResponse")]
        System.Threading.Tasks.Task Pedido_EliminarAsync(int idEmpresa, int codigoUsuario, int idOperacion, string password);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pedido_Listar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pedido_ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> idEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int codigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idAgenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.DateTime fechaFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Nullable<int> idDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string idVendedor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public System.Nullable<int> idFormaPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public System.Nullable<decimal> estadoAprobacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public bool superUsuario;
        
        public Pedido_ListarRequest() {
        }
        
        public Pedido_ListarRequest(System.Nullable<int> idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, System.Nullable<int> idDocumento, string idVendedor, System.Nullable<int> idFormaPago, System.Nullable<decimal> estadoAprobacion, bool superUsuario) {
            this.idEmpresa = idEmpresa;
            this.codigoUsuario = codigoUsuario;
            this.idAgenda = idAgenda;
            this.fechaInicio = fechaInicio;
            this.fechaFinal = fechaFinal;
            this.idDocumento = idDocumento;
            this.idVendedor = idVendedor;
            this.idFormaPago = idFormaPago;
            this.estadoAprobacion = estadoAprobacion;
            this.superUsuario = superUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pedido_ListarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Pedido_ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GS.SISGEGS.DM.gsPedido_ListarResult[] Pedido_ListarResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool superUsuario;
        
        public Pedido_ListarResponse() {
        }
        
        public Pedido_ListarResponse(GS.SISGEGS.DM.gsPedido_ListarResult[] Pedido_ListarResult, bool superUsuario) {
            this.Pedido_ListarResult = Pedido_ListarResult;
            this.superUsuario = superUsuario;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoWCFChannel : GS.SISGEGS.Web.PedidoWCF.IPedidoWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.PedidoWCF.IPedidoWCF>, GS.SISGEGS.Web.PedidoWCF.IPedidoWCF {
        
        public PedidoWCFClient() {
        }
        
        public PedidoWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.VBG03630Result[] Pedido_ListarTipo(int idEmpresa, int codigoUsuario) {
            return base.Channel.Pedido_ListarTipo(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.VBG03630Result[]> Pedido_ListarTipoAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Pedido_ListarTipoAsync(idEmpresa, codigoUsuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GS.SISGEGS.Web.PedidoWCF.Pedido_ListarResponse GS.SISGEGS.Web.PedidoWCF.IPedidoWCF.Pedido_Listar(GS.SISGEGS.Web.PedidoWCF.Pedido_ListarRequest request) {
            return base.Channel.Pedido_Listar(request);
        }
        
        public GS.SISGEGS.DM.gsPedido_ListarResult[] Pedido_Listar(System.Nullable<int> idEmpresa, int codigoUsuario, string idAgenda, System.DateTime fechaInicio, System.DateTime fechaFinal, System.Nullable<int> idDocumento, string idVendedor, System.Nullable<int> idFormaPago, System.Nullable<decimal> estadoAprobacion, ref bool superUsuario) {
            GS.SISGEGS.Web.PedidoWCF.Pedido_ListarRequest inValue = new GS.SISGEGS.Web.PedidoWCF.Pedido_ListarRequest();
            inValue.idEmpresa = idEmpresa;
            inValue.codigoUsuario = codigoUsuario;
            inValue.idAgenda = idAgenda;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFinal = fechaFinal;
            inValue.idDocumento = idDocumento;
            inValue.idVendedor = idVendedor;
            inValue.idFormaPago = idFormaPago;
            inValue.estadoAprobacion = estadoAprobacion;
            inValue.superUsuario = superUsuario;
            GS.SISGEGS.Web.PedidoWCF.Pedido_ListarResponse retVal = ((GS.SISGEGS.Web.PedidoWCF.IPedidoWCF)(this)).Pedido_Listar(inValue);
            superUsuario = retVal.superUsuario;
            return retVal.Pedido_ListarResult;
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.Web.PedidoWCF.Pedido_ListarResponse> Pedido_ListarAsync(GS.SISGEGS.Web.PedidoWCF.Pedido_ListarRequest request) {
            return base.Channel.Pedido_ListarAsync(request);
        }
        
        public void Pedido_Registrar(int idEmpresa, int codigoUsuario, GS.SISGEGS.BE.PedidoCabBE objPedidoCabBE, GS.SISGEGS.BE.PedidoDetBE[] lstProductos, GS.SISGEGS.BE.GlosaBE[] lstImpuestos, System.Nullable<decimal> idOperacion, string password, decimal limiteCredito) {
            base.Channel.Pedido_Registrar(idEmpresa, codigoUsuario, objPedidoCabBE, lstProductos, lstImpuestos, idOperacion, password, limiteCredito);
        }
        
        public System.Threading.Tasks.Task Pedido_RegistrarAsync(int idEmpresa, int codigoUsuario, GS.SISGEGS.BE.PedidoCabBE objPedidoCabBE, GS.SISGEGS.BE.PedidoDetBE[] lstProductos, GS.SISGEGS.BE.GlosaBE[] lstImpuestos, System.Nullable<decimal> idOperacion, string password, decimal limiteCredito) {
            return base.Channel.Pedido_RegistrarAsync(idEmpresa, codigoUsuario, objPedidoCabBE, lstProductos, lstImpuestos, idOperacion, password, limiteCredito);
        }
        
        public GS.SISGEGS.DM.gsPedido_BuscarCabeceraResult Pedido_BuscarCabecera(int idEmpresa, int codigoUsuario, int idPedido) {
            return base.Channel.Pedido_BuscarCabecera(idEmpresa, codigoUsuario, idPedido);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPedido_BuscarCabeceraResult> Pedido_BuscarCabeceraAsync(int idEmpresa, int codigoUsuario, int idPedido) {
            return base.Channel.Pedido_BuscarCabeceraAsync(idEmpresa, codigoUsuario, idPedido);
        }
        
        public GS.SISGEGS.DM.gsPedido_BuscarDetalleResult[] Pedido_BuscarDetalle(int idEmpresa, int codigoUsuario, int idPedido, System.Nullable<decimal> idAlmacen) {
            return base.Channel.Pedido_BuscarDetalle(idEmpresa, codigoUsuario, idPedido, idAlmacen);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPedido_BuscarDetalleResult[]> Pedido_BuscarDetalleAsync(int idEmpresa, int codigoUsuario, int idPedido, System.Nullable<decimal> idAlmacen) {
            return base.Channel.Pedido_BuscarDetalleAsync(idEmpresa, codigoUsuario, idPedido, idAlmacen);
        }
        
        public void Pedido_Eliminar(int idEmpresa, int codigoUsuario, int idOperacion, string password) {
            base.Channel.Pedido_Eliminar(idEmpresa, codigoUsuario, idOperacion, password);
        }
        
        public System.Threading.Tasks.Task Pedido_EliminarAsync(int idEmpresa, int codigoUsuario, int idOperacion, string password) {
            return base.Channel.Pedido_EliminarAsync(idEmpresa, codigoUsuario, idOperacion, password);
        }
    }
}
