//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.DM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVROJAS\\SQLSERVER2014;Initial Catalog=db0grpsil;Persist Security Inf" +
            "o=True;User ID=sa;Password=P@$$w0rd")]
        public string db0grpsilConnectionString {
            get {
                return ((string)(this["db0grpsilConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC;Persist Security Info=True;User ID=sa;P" +
            "assword=Sistemas1912")]
        public string RECConnectionString {
            get {
                return ((string)(this["RECConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC;Persist Security Info=True;User ID=usrG" +
            "EN0016;Password=123456")]
        public string RECConnectionString1 {
            get {
                return ((string)(this["RECConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0dev;User ID=sa;Password=Sistemas1912")]
        public string gs0devConnectionString1 {
            get {
                return ((string)(this["gs0devConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;Persist Security Info=True;User ID=sa")]
        public string REC2ConnectionString {
            get {
                return ((string)(this["REC2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0dev;Persist Security Info=True;User ID=s" +
            "a;Password=Sistemas1912")]
        public string gs0devConnectionString2 {
            get {
                return ((string)(this["gs0devConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0dev;Persist Security Info=True;User ID=s" +
            "a")]
        public string gs0devConnectionString3 {
            get {
                return ((string)(this["gs0devConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0dev;User ID=sa;Password=Sistemas1912")]
        public string gs0devConnectionString {
            get {
                return ((string)(this["gs0devConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0genesys;Persist Security Info=True;User " +
            "ID=sa")]
        public string gs0genesysConnectionString1 {
            get {
                return ((string)(this["gs0genesysConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;Persist Security Info=True;User ID=sa;" +
            "Password=Sistemas1912")]
        public string REC2ConnectionString2 {
            get {
                return ((string)(this["REC2ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC;Persist Security Info=True;User ID=sa")]
        public string RECConnectionString2 {
            get {
                return ((string)(this["RECConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;User ID=sa")]
        public string REC2ConnectionString3 {
            get {
                return ((string)(this["REC2ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;Persist Security Info=True;User ID=sa")]
        public string NeoAgrum_SACConnectionString {
            get {
                return ((string)(this["NeoAgrum_SACConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=Silvestre_Peru_SAC;Persist Security Info=Tr" +
            "ue;User ID=sa")]
        public string NeoAgrum_SACConnectionString1 {
            get {
                return ((string)(this["NeoAgrum_SACConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0genesys;Persist Security Info=True;User " +
            "ID=sa")]
        public string gs0genesysConnectionString {
            get {
                return ((string)(this["gs0genesysConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;Persist Security Info=True;User ID=sa")]
        public string REC2ConnectionString1 {
            get {
                return ((string)(this["REC2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;Persist Security Info=True;User ID=sa")]
        public string Silvestre_Peru_SACConnectionString1 {
            get {
                return ((string)(this["Silvestre_Peru_SACConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=NeoAgrum_SAC;User ID=sa")]
        public string NeoAgrum_SACConnectionString2 {
            get {
                return ((string)(this["NeoAgrum_SACConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;Persist Security Info=True;User ID=sa")]
        public string Silvestre_Peru_SACConnectionString2 {
            get {
                return ((string)(this["Silvestre_Peru_SACConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC2;User ID=sa;Password=Sistemas1912")]
        public string Silvestre_Peru_SACConnectionString {
            get {
                return ((string)(this["Silvestre_Peru_SACConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0genesys;Persist Security Info=True;User " +
            "ID=sa")]
        public string gs0genesysConnectionString2 {
            get {
                return ((string)(this["gs0genesysConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=NeoAgrum_SAC;User ID=sa;Password=Sistemas19" +
            "12")]
        public string NeoAgrum_SACConnectionString3 {
            get {
                return ((string)(this["NeoAgrum_SACConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=Inatec_Peru_SAC;User ID=sa;Password=Sistema" +
            "s1912")]
        public string Inatec_Peru_SACConnectionString {
            get {
                return ((string)(this["Inatec_Peru_SACConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=NeoAgrum_SAC;Persist Security Info=True;Use" +
            "r ID=sa;Password=Sistemas1912")]
        public string NeoAgrum_SACConnectionString4 {
            get {
                return ((string)(this["NeoAgrum_SACConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=Silvestre_Peru_SAC;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=Sistemas1912")]
        public string Silvestre_Peru_SACConnectionString3 {
            get {
                return ((string)(this["Silvestre_Peru_SACConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=Silvestre_Peru_SAC;User ID=sa;Password=Sist" +
            "emas1912")]
        public string Silvestre_Peru_SACConnectionString4 {
            get {
                return ((string)(this["Silvestre_Peru_SACConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0genesys;Persist Security Info=True;User " +
            "ID=sa;Password=Sistemas1912")]
        public string gs0genesysConnectionString3 {
            get {
                return ((string)(this["gs0genesysConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=Inatec_Peru_SAC;Persist Security Info=True;" +
            "User ID=sa;Password=Sistemas1912")]
        public string Inatec_Peru_SACConnectionString1 {
            get {
                return ((string)(this["Inatec_Peru_SACConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=Silvestre_Peru_SAC;Persist Security Info=Tr" +
            "ue;User ID=aplicacionesgs;Password=desarrollo2017")]
        public string Silvestre_Peru_SACConnectionString5 {
            get {
                return ((string)(this["Silvestre_Peru_SACConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC_NEO;User ID=aplicacionesgs;Password=des" +
            "arrollo2017")]
        public string REC_NEOConnectionString {
            get {
                return ((string)(this["REC_NEOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=Silvestre_Peru_SAC;User ID=aplicacionesgs;P" +
            "assword=desarrollo2017")]
        public string Silvestre_Peru_SACConnectionString6 {
            get {
                return ((string)(this["Silvestre_Peru_SACConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=gs0genesys;User ID=aplicacionesgs;Password=" +
            "desarrollo2017")]
        public string gs0genesysConnectionString4 {
            get {
                return ((string)(this["gs0genesysConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC_Sil;User ID=aplicacionesgs;Password=des" +
            "arrollo2017")]
        public string REC_SilConnectionString {
            get {
                return ((string)(this["REC_SilConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC_Sil2;User ID=aplicacionesgs;Password=de" +
            "sarrollo2017")]
        public string REC_Sil2ConnectionString {
            get {
                return ((string)(this["REC_Sil2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.1.8;Initial Catalog=REC_Sil3;User ID=aplicacionesgs;Password=de" +
            "sarrollo2017")]
        public string REC_Sil3ConnectionString {
            get {
                return ((string)(this["REC_Sil3ConnectionString"]));
            }
        }
    }
}
