//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.Web.ReporteVentaWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReporteVentaWCF.IReporteVentaWCF")]
    public interface IReporteVentaWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_VendedorZona", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_VendedorZonaResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorV2Result[] DocVenta_ReporteVenta_VendedorZona(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_VendedorZona", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_VendedorZonaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorV2Result[]> DocVenta_ReporteVenta_VendedorZonaAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Vendedor", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_VendedorResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorResult[] DocVenta_ReporteVenta_Vendedor(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Vendedor", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_VendedorResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorResult[]> DocVenta_ReporteVenta_VendedorAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Cliente", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_ClienteResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ClienteResult[] DocVenta_ReporteVenta_Cliente(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal, string ESTADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Cliente", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_ClienteResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ClienteResult[]> DocVenta_ReporteVenta_ClienteAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal, string ESTADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Producto", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_ProductoResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ProductoResult[] DocVenta_ReporteVenta_Producto(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Producto", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_ProductoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ProductoResult[]> DocVenta_ReporteVenta_ProductoAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Fecha", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_FechaResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_FechaResult[] DocVenta_ReporteVenta_Fecha(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Fecha", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_FechaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_FechaResult[]> DocVenta_ReporteVenta_FechaAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaResult[] DocVenta_ReporteVenta_Marca(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaResult[]> DocVenta_ReporteVenta_MarcaAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProducto", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProductoResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProductoResult[] DocVenta_ReporteVenta_MarcaProducto(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProducto", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProductoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProductoResult[]> DocVenta_ReporteVenta_MarcaProductoAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaMarca", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaMarcaResponse")]
        GS.SISGEGS.DM.gsDocVenta_ConsultarVentaMarcaResult[] DocVenta_ConsultarVentaMarca(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaMarca", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaMarcaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ConsultarVentaMarcaResult[]> DocVenta_ConsultarVentaMarcaAsync(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaCliente", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaClienteResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaClienteResult[] DocVenta_ReporteVenta_MarcaCliente(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaCliente", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaClienteResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaClienteResult[]> DocVenta_ReporteVenta_MarcaClienteAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedor", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedorResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedorResult[] DocVenta_ReporteVenta_MarcaVendedor(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedor", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedorResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedorResult[]> DocVenta_ReporteVenta_MarcaVendedorAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaProducto", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaProductoResponse")]
        GS.SISGEGS.DM.gsDocVenta_ConsultarVentaProductoResult[] DocVenta_ConsultarVentaProducto(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaProducto", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ConsultarVentaProductoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ConsultarVentaProductoResult[]> DocVenta_ConsultarVentaProductoAsync(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporte_ProyeccionVentasPareto", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporte_ProyeccionVentasParetoResponse")]
        GS.SISGEGS.DM.gsReporte_ProyeccionVentasParetoResult[] gsReporte_ProyeccionVentasPareto(int idEmpresa, int codigoUsuario, int anhoAnterior, int AnhoActual, int mesInicio, int mesFinal, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporte_ProyeccionVentasPareto", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporte_ProyeccionVentasParetoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporte_ProyeccionVentasParetoResult[]> gsReporte_ProyeccionVentasParetoAsync(int idEmpresa, int codigoUsuario, int anhoAnterior, int AnhoActual, int mesInicio, int mesFinal, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_Registrar", ReplyAction="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_RegistrarResponse")]
        void ProyectadoVentas_Registrar(
                    int idEmpresa, 
                    int codigoUsuario, 
                    int ID_Pronostico, 
                    System.DateTime Fecha, 
                    int Id_Item, 
                    decimal precio, 
                    decimal costo, 
                    int cantidad, 
                    decimal importe, 
                    bool aprobacion, 
                    int anho, 
                    int mes, 
                    int Id_Zona, 
                    string Id_Vendedor, 
                    string Id_Cliente, 
                    int moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_Registrar", ReplyAction="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_RegistrarResponse")]
        System.Threading.Tasks.Task ProyectadoVentas_RegistrarAsync(
                    int idEmpresa, 
                    int codigoUsuario, 
                    int ID_Pronostico, 
                    System.DateTime Fecha, 
                    int Id_Item, 
                    decimal precio, 
                    decimal costo, 
                    int cantidad, 
                    decimal importe, 
                    bool aprobacion, 
                    int anho, 
                    int mes, 
                    int Id_Zona, 
                    string Id_Vendedor, 
                    string Id_Cliente, 
                    int moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporte_PronosticoVentas", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporte_PronosticoVentasResponse")]
        GS.SISGEGS.DM.gsReporteVentaPresupuesto_ProductoResult[] gsReporte_PronosticoVentas(int idEmpresa, int codigoUsuario, int anho, int mes, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporte_PronosticoVentas", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporte_PronosticoVentasResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporteVentaPresupuesto_ProductoResult[]> gsReporte_PronosticoVentasAsync(int idEmpresa, int codigoUsuario, int anho, int mes, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_MarcaResponse")]
        GS.SISGEGS.DM.gsPronostico_Reporte_MarcaResult[] Pronostico_Reporte_Marca(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_MarcaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_Reporte_MarcaResult[]> Pronostico_Reporte_MarcaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_Vendedor", ReplyAction="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_VendedorResponse")]
        GS.SISGEGS.DM.gsPronostico_Reporte_VendedorResult[] Pronostico_Reporte_Vendedor(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_Vendedor", ReplyAction="http://tempuri.org/IReporteVentaWCF/Pronostico_Reporte_VendedorResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_Reporte_VendedorResult[]> Pronostico_Reporte_VendedorAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_RegistrarBulkCopy", ReplyAction="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_RegistrarBulkCopyResponse")]
        void ProyectadoVentas_RegistrarBulkCopy(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_RegistrarBulkCopy", ReplyAction="http://tempuri.org/IReporteVentaWCF/ProyectadoVentas_RegistrarBulkCopyResponse")]
        System.Threading.Tasks.Task ProyectadoVentas_RegistrarBulkCopyAsync(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Pronostico_Planeamiento_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/Pronostico_Planeamiento_MarcaResponse")]
        GS.SISGEGS.DM.gsPronostico_Reporte_Planeamiento_MarcaResult[] Pronostico_Planeamiento_Marca(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Pronostico_Planeamiento_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/Pronostico_Planeamiento_MarcaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_Reporte_Planeamiento_MarcaResult[]> Pronostico_Planeamiento_MarcaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporte_PresupuestoVentasPareto", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporte_PresupuestoVentasParetoResponse")]
        GS.SISGEGS.DM.gsReporte_PresupuestoVentasParetoResult[] gsReporte_PresupuestoVentasPareto(int idEmpresa, int codigoUsuario, int anho1, int anho2, int mes1, int mes2, int id_zona, string id_vendedor, bool flag_semillas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporte_PresupuestoVentasPareto", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporte_PresupuestoVentasParetoResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporte_PresupuestoVentasParetoResult[]> gsReporte_PresupuestoVentasParetoAsync(int idEmpresa, int codigoUsuario, int anho1, int anho2, int mes1, int mes2, int id_zona, string id_vendedor, bool flag_semillas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporteVentaPresupuesto_Producto2017", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporteVentaPresupuesto_Producto2017Respons" +
            "e")]
        GS.SISGEGS.DM.gsReporteVentaPresupuesto_Producto2017Result[] gsReporteVentaPresupuesto_Producto2017(int idEmpresa, int codigoUsuario, int anho, int mes, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsReporteVentaPresupuesto_Producto2017", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsReporteVentaPresupuesto_Producto2017Respons" +
            "e")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporteVentaPresupuesto_Producto2017Result[]> gsReporteVentaPresupuesto_Producto2017Async(int idEmpresa, int codigoUsuario, int anho, int mes, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/PresupuestadoVentas_RegistrarBulkCopy", ReplyAction="http://tempuri.org/IReporteVentaWCF/PresupuestadoVentas_RegistrarBulkCopyResponse" +
            "")]
        void PresupuestadoVentas_RegistrarBulkCopy(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/PresupuestadoVentas_RegistrarBulkCopy", ReplyAction="http://tempuri.org/IReporteVentaWCF/PresupuestadoVentas_RegistrarBulkCopyResponse" +
            "")]
        System.Threading.Tasks.Task PresupuestadoVentas_RegistrarBulkCopyAsync(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsPronostico_vs_Real", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsPronostico_vs_RealResponse")]
        GS.SISGEGS.DM.gsPronostico_vs_RealResult[] gsPronostico_vs_Real(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsPronostico_vs_Real", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsPronostico_vs_RealResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_vs_RealResult[]> gsPronostico_vs_RealAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaInatecResponse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_Marca_InatecResult[] DocVenta_ReporteVenta_MarcaInatec(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaInatecResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_Marca_InatecResult[]> DocVenta_ReporteVenta_MarcaInatecAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProductoInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProductoInatecResp" +
            "onse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProducto_InatecResult[] DocVenta_ReporteVenta_MarcaProductoInatec(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProductoInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaProductoInatecResp" +
            "onse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProducto_InatecResult[]> DocVenta_ReporteVenta_MarcaProductoInatecAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Presupuesto_Zona", ReplyAction="http://tempuri.org/IReporteVentaWCF/Presupuesto_ZonaResponse")]
        GS.SISGEGS.DM.gsPresupuesto_ZonaResult[] Presupuesto_Zona(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Presupuesto_Zona", ReplyAction="http://tempuri.org/IReporteVentaWCF/Presupuesto_ZonaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPresupuesto_ZonaResult[]> Presupuesto_ZonaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaClienteInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaClienteInatecRespo" +
            "nse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaCliente_InatecResult[] DocVenta_ReporteVenta_MarcaClienteInatec(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaClienteInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaClienteInatecRespo" +
            "nse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaCliente_InatecResult[]> DocVenta_ReporteVenta_MarcaClienteInatecAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedorInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedorInatecResp" +
            "onse")]
        GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedor_InatecResult[] DocVenta_ReporteVenta_MarcaVendedorInatec(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedorInatec", ReplyAction="http://tempuri.org/IReporteVentaWCF/DocVenta_ReporteVenta_MarcaVendedorInatecResp" +
            "onse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedor_InatecResult[]> DocVenta_ReporteVenta_MarcaVendedorInatecAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Presupuesto_Reporte_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/Presupuesto_Reporte_MarcaResponse")]
        GS.SISGEGS.DM.gsPresupuesto_Reporte_MarcaResult[] Presupuesto_Reporte_Marca(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Presupuesto_Reporte_Marca", ReplyAction="http://tempuri.org/IReporteVentaWCF/Presupuesto_Reporte_MarcaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPresupuesto_Reporte_MarcaResult[]> Presupuesto_Reporte_MarcaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsVentaPronostico_vs_Real", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsVentaPronostico_vs_RealResponse")]
        GS.SISGEGS.DM.gsVentaPronostico_vs_RealResult[] gsVentaPronostico_vs_Real(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/gsVentaPronostico_vs_Real", ReplyAction="http://tempuri.org/IReporteVentaWCF/gsVentaPronostico_vs_RealResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVentaPronostico_vs_RealResult[]> gsVentaPronostico_vs_RealAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Familia", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_FamiliaResponse")]
        GS.SISGEGS.DM.ReporteVentas_FamiliaResult[] ReporteVentas_Familia(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Familia", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_FamiliaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_FamiliaResult[]> ReporteVentas_FamiliaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Items", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_ItemsResponse")]
        GS.SISGEGS.DM.ReporteVentas_ItemsResult[] ReporteVentas_Items(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Items", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_ItemsResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_ItemsResult[]> ReporteVentas_ItemsAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Zonas", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_ZonasResponse")]
        GS.SISGEGS.DM.ReporteVentas_ZonasResult[] ReporteVentas_Zonas(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Zonas", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_ZonasResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_ZonasResult[]> ReporteVentas_ZonasAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReportesIntranet_Lista", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReportesIntranet_ListaResponse")]
        GS.SISGEGS.DM.ReportesIntranet_ListarResult[] ReportesIntranet_Lista(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReportesIntranet_Lista", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReportesIntranet_ListaResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ReportesIntranet_ListarResult[]> ReportesIntranet_ListaAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/PermisosUsuarios_ListarResult", ReplyAction="http://tempuri.org/IReporteVentaWCF/PermisosUsuarios_ListarResultResponse")]
        GS.SISGEGS.DM.PermisosUsuarios_ListarResult[] PermisosUsuarios_ListarResult(int idEmpresa, int codigoUsuario, string texto, int reporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/PermisosUsuarios_ListarResult", ReplyAction="http://tempuri.org/IReporteVentaWCF/PermisosUsuarios_ListarResultResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.PermisosUsuarios_ListarResult[]> PermisosUsuarios_ListarResultAsync(int idEmpresa, int codigoUsuario, string texto, int reporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ZonaPersonal_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/ZonaPersonal_ListarResponse")]
        GS.SISGEGS.DM.ZonasPermisos_ListarResult[] ZonaPersonal_Listar(int idEmpresa, int codigoUsuario, int id_Permiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ZonaPersonal_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/ZonaPersonal_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ZonasPermisos_ListarResult[]> ZonaPersonal_ListarAsync(int idEmpresa, int codigoUsuario, int id_Permiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Zona_Registrar", ReplyAction="http://tempuri.org/IReporteVentaWCF/Zona_RegistrarResponse")]
        void Zona_Registrar(int idEmpresa, int codigoUsuario, int idPermiso, int id_zona, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Zona_Registrar", ReplyAction="http://tempuri.org/IReporteVentaWCF/Zona_RegistrarResponse")]
        System.Threading.Tasks.Task Zona_RegistrarAsync(int idEmpresa, int codigoUsuario, int idPermiso, int id_zona, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Zonas_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/Zonas_ListarResponse")]
        GS.SISGEGS.DM.Zonas_ReportesResult[] Zonas_Listar(int idEmpresa, int codigoUsuario, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Zonas_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/Zonas_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.Zonas_ReportesResult[]> Zonas_ListarAsync(int idEmpresa, int codigoUsuario, int id_zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/UsuarioReporte_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/UsuarioReporte_ListarResponse")]
        GS.SISGEGS.DM.UsuarioReporte_ListarResult[] UsuarioReporte_Listar(int idEmpresa, int codigoUsuario, int idUsuario, string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/UsuarioReporte_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/UsuarioReporte_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.UsuarioReporte_ListarResult[]> UsuarioReporte_ListarAsync(int idEmpresa, int codigoUsuario, int idUsuario, string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ZonasReporte_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/ZonasReporte_ListarResponse")]
        GS.SISGEGS.DM.ZonasReporte_ListarResult[] ZonasReporte_Listar(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ZonasReporte_Listar", ReplyAction="http://tempuri.org/IReporteVentaWCF/ZonasReporte_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ZonasReporte_ListarResult[]> ZonasReporte_ListarAsync(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/PermisosReportes_Registrar", ReplyAction="http://tempuri.org/IReporteVentaWCF/PermisosReportes_RegistrarResponse")]
        int PermisosReportes_Registrar(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte, int Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/PermisosReportes_Registrar", ReplyAction="http://tempuri.org/IReporteVentaWCF/PermisosReportes_RegistrarResponse")]
        System.Threading.Tasks.Task<int> PermisosReportes_RegistrarAsync(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte, int Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_R3_1", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_R3_1Response")]
        GS.SISGEGS.DM.ReporteVentas_R3_1Result[] ReporteVentas_R3_1(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_R3_1", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_R3_1Response")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_R3_1Result[]> ReporteVentas_R3_1Async(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Resultados", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_ResultadosResponse")]
        GS.SISGEGS.DM.ReporteVentas_EstadoResultadosResult[] ReporteVentas_Resultados(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona, string NombreUnidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/ReporteVentas_Resultados", ReplyAction="http://tempuri.org/IReporteVentaWCF/ReporteVentas_ResultadosResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_EstadoResultadosResult[]> ReporteVentas_ResultadosAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona, string NombreUnidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Listar_Zona_BI", ReplyAction="http://tempuri.org/IReporteVentaWCF/Listar_Zona_BIResponse")]
        GS.SISGEGS.DM.Listar_Zona_BIResult[] Listar_Zona_BI(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Listar_Zona_BI", ReplyAction="http://tempuri.org/IReporteVentaWCF/Listar_Zona_BIResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.Listar_Zona_BIResult[]> Listar_Zona_BIAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Listar_Unidad_BI", ReplyAction="http://tempuri.org/IReporteVentaWCF/Listar_Unidad_BIResponse")]
        GS.SISGEGS.DM.Listar_Unidad_BIResult[] Listar_Unidad_BI(int idEmpresa, int codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporteVentaWCF/Listar_Unidad_BI", ReplyAction="http://tempuri.org/IReporteVentaWCF/Listar_Unidad_BIResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.Listar_Unidad_BIResult[]> Listar_Unidad_BIAsync(int idEmpresa, int codigoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReporteVentaWCFChannel : GS.SISGEGS.Web.ReporteVentaWCF.IReporteVentaWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteVentaWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.Web.ReporteVentaWCF.IReporteVentaWCF>, GS.SISGEGS.Web.ReporteVentaWCF.IReporteVentaWCF {
        
        public ReporteVentaWCFClient() {
        }
        
        public ReporteVentaWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteVentaWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteVentaWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteVentaWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorV2Result[] DocVenta_ReporteVenta_VendedorZona(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_VendedorZona(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorV2Result[]> DocVenta_ReporteVenta_VendedorZonaAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_VendedorZonaAsync(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorResult[] DocVenta_ReporteVenta_Vendedor(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_Vendedor(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_VendedorResult[]> DocVenta_ReporteVenta_VendedorAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_VendedorAsync(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ClienteResult[] DocVenta_ReporteVenta_Cliente(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal, string ESTADO) {
            return base.Channel.DocVenta_ReporteVenta_Cliente(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal, ESTADO);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ClienteResult[]> DocVenta_ReporteVenta_ClienteAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal, string ESTADO) {
            return base.Channel.DocVenta_ReporteVenta_ClienteAsync(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal, ESTADO);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ProductoResult[] DocVenta_ReporteVenta_Producto(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_Producto(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_ProductoResult[]> DocVenta_ReporteVenta_ProductoAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_ProductoAsync(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_FechaResult[] DocVenta_ReporteVenta_Fecha(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_Fecha(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_FechaResult[]> DocVenta_ReporteVenta_FechaAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_FechaAsync(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaResult[] DocVenta_ReporteVenta_Marca(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_Marca(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaResult[]> DocVenta_ReporteVenta_MarcaAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaAsync(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProductoResult[] DocVenta_ReporteVenta_MarcaProducto(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaProducto(idEmpresa, codigoUsuario, ID_Marca, ID_Zona, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProductoResult[]> DocVenta_ReporteVenta_MarcaProductoAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaProductoAsync(idEmpresa, codigoUsuario, ID_Marca, ID_Zona, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ConsultarVentaMarcaResult[] DocVenta_ConsultarVentaMarca(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ConsultarVentaMarca(idEmpresa, codigoUsuario, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ConsultarVentaMarcaResult[]> DocVenta_ConsultarVentaMarcaAsync(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ConsultarVentaMarcaAsync(idEmpresa, codigoUsuario, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaClienteResult[] DocVenta_ReporteVenta_MarcaCliente(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaCliente(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaClienteResult[]> DocVenta_ReporteVenta_MarcaClienteAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaClienteAsync(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedorResult[] DocVenta_ReporteVenta_MarcaVendedor(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaVendedor(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedorResult[]> DocVenta_ReporteVenta_MarcaVendedorAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaVendedorAsync(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ConsultarVentaProductoResult[] DocVenta_ConsultarVentaProducto(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ConsultarVentaProducto(idEmpresa, codigoUsuario, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ConsultarVentaProductoResult[]> DocVenta_ConsultarVentaProductoAsync(int idEmpresa, int codigoUsuario, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ConsultarVentaProductoAsync(idEmpresa, codigoUsuario, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsReporte_ProyeccionVentasParetoResult[] gsReporte_ProyeccionVentasPareto(int idEmpresa, int codigoUsuario, int anhoAnterior, int AnhoActual, int mesInicio, int mesFinal, int id_zona) {
            return base.Channel.gsReporte_ProyeccionVentasPareto(idEmpresa, codigoUsuario, anhoAnterior, AnhoActual, mesInicio, mesFinal, id_zona);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporte_ProyeccionVentasParetoResult[]> gsReporte_ProyeccionVentasParetoAsync(int idEmpresa, int codigoUsuario, int anhoAnterior, int AnhoActual, int mesInicio, int mesFinal, int id_zona) {
            return base.Channel.gsReporte_ProyeccionVentasParetoAsync(idEmpresa, codigoUsuario, anhoAnterior, AnhoActual, mesInicio, mesFinal, id_zona);
        }
        
        public void ProyectadoVentas_Registrar(
                    int idEmpresa, 
                    int codigoUsuario, 
                    int ID_Pronostico, 
                    System.DateTime Fecha, 
                    int Id_Item, 
                    decimal precio, 
                    decimal costo, 
                    int cantidad, 
                    decimal importe, 
                    bool aprobacion, 
                    int anho, 
                    int mes, 
                    int Id_Zona, 
                    string Id_Vendedor, 
                    string Id_Cliente, 
                    int moneda) {
            base.Channel.ProyectadoVentas_Registrar(idEmpresa, codigoUsuario, ID_Pronostico, Fecha, Id_Item, precio, costo, cantidad, importe, aprobacion, anho, mes, Id_Zona, Id_Vendedor, Id_Cliente, moneda);
        }
        
        public System.Threading.Tasks.Task ProyectadoVentas_RegistrarAsync(
                    int idEmpresa, 
                    int codigoUsuario, 
                    int ID_Pronostico, 
                    System.DateTime Fecha, 
                    int Id_Item, 
                    decimal precio, 
                    decimal costo, 
                    int cantidad, 
                    decimal importe, 
                    bool aprobacion, 
                    int anho, 
                    int mes, 
                    int Id_Zona, 
                    string Id_Vendedor, 
                    string Id_Cliente, 
                    int moneda) {
            return base.Channel.ProyectadoVentas_RegistrarAsync(idEmpresa, codigoUsuario, ID_Pronostico, Fecha, Id_Item, precio, costo, cantidad, importe, aprobacion, anho, mes, Id_Zona, Id_Vendedor, Id_Cliente, moneda);
        }
        
        public GS.SISGEGS.DM.gsReporteVentaPresupuesto_ProductoResult[] gsReporte_PronosticoVentas(int idEmpresa, int codigoUsuario, int anho, int mes, int id_zona) {
            return base.Channel.gsReporte_PronosticoVentas(idEmpresa, codigoUsuario, anho, mes, id_zona);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporteVentaPresupuesto_ProductoResult[]> gsReporte_PronosticoVentasAsync(int idEmpresa, int codigoUsuario, int anho, int mes, int id_zona) {
            return base.Channel.gsReporte_PronosticoVentasAsync(idEmpresa, codigoUsuario, anho, mes, id_zona);
        }
        
        public GS.SISGEGS.DM.gsPronostico_Reporte_MarcaResult[] Pronostico_Reporte_Marca(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Pronostico_Reporte_Marca(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_Reporte_MarcaResult[]> Pronostico_Reporte_MarcaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Pronostico_Reporte_MarcaAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.gsPronostico_Reporte_VendedorResult[] Pronostico_Reporte_Vendedor(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Pronostico_Reporte_Vendedor(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_Reporte_VendedorResult[]> Pronostico_Reporte_VendedorAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Pronostico_Reporte_VendedorAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public void ProyectadoVentas_RegistrarBulkCopy(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla) {
            base.Channel.ProyectadoVentas_RegistrarBulkCopy(idEmpresa, codigoUsuario, Fecha, Id_Zona, Id_Vendedor, Id_Cliente, moneda, tabla);
        }
        
        public System.Threading.Tasks.Task ProyectadoVentas_RegistrarBulkCopyAsync(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla) {
            return base.Channel.ProyectadoVentas_RegistrarBulkCopyAsync(idEmpresa, codigoUsuario, Fecha, Id_Zona, Id_Vendedor, Id_Cliente, moneda, tabla);
        }
        
        public GS.SISGEGS.DM.gsPronostico_Reporte_Planeamiento_MarcaResult[] Pronostico_Planeamiento_Marca(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Pronostico_Planeamiento_Marca(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_Reporte_Planeamiento_MarcaResult[]> Pronostico_Planeamiento_MarcaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Pronostico_Planeamiento_MarcaAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.gsReporte_PresupuestoVentasParetoResult[] gsReporte_PresupuestoVentasPareto(int idEmpresa, int codigoUsuario, int anho1, int anho2, int mes1, int mes2, int id_zona, string id_vendedor, bool flag_semillas) {
            return base.Channel.gsReporte_PresupuestoVentasPareto(idEmpresa, codigoUsuario, anho1, anho2, mes1, mes2, id_zona, id_vendedor, flag_semillas);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporte_PresupuestoVentasParetoResult[]> gsReporte_PresupuestoVentasParetoAsync(int idEmpresa, int codigoUsuario, int anho1, int anho2, int mes1, int mes2, int id_zona, string id_vendedor, bool flag_semillas) {
            return base.Channel.gsReporte_PresupuestoVentasParetoAsync(idEmpresa, codigoUsuario, anho1, anho2, mes1, mes2, id_zona, id_vendedor, flag_semillas);
        }
        
        public GS.SISGEGS.DM.gsReporteVentaPresupuesto_Producto2017Result[] gsReporteVentaPresupuesto_Producto2017(int idEmpresa, int codigoUsuario, int anho, int mes, string id_vendedor) {
            return base.Channel.gsReporteVentaPresupuesto_Producto2017(idEmpresa, codigoUsuario, anho, mes, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsReporteVentaPresupuesto_Producto2017Result[]> gsReporteVentaPresupuesto_Producto2017Async(int idEmpresa, int codigoUsuario, int anho, int mes, string id_vendedor) {
            return base.Channel.gsReporteVentaPresupuesto_Producto2017Async(idEmpresa, codigoUsuario, anho, mes, id_vendedor);
        }
        
        public void PresupuestadoVentas_RegistrarBulkCopy(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla) {
            base.Channel.PresupuestadoVentas_RegistrarBulkCopy(idEmpresa, codigoUsuario, Fecha, Id_Zona, Id_Vendedor, Id_Cliente, moneda, tabla);
        }
        
        public System.Threading.Tasks.Task PresupuestadoVentas_RegistrarBulkCopyAsync(int idEmpresa, int codigoUsuario, System.DateTime Fecha, int Id_Zona, string Id_Vendedor, string Id_Cliente, int moneda, System.Data.DataTable tabla) {
            return base.Channel.PresupuestadoVentas_RegistrarBulkCopyAsync(idEmpresa, codigoUsuario, Fecha, Id_Zona, Id_Vendedor, Id_Cliente, moneda, tabla);
        }
        
        public GS.SISGEGS.DM.gsPronostico_vs_RealResult[] gsPronostico_vs_Real(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.gsPronostico_vs_Real(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPronostico_vs_RealResult[]> gsPronostico_vs_RealAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.gsPronostico_vs_RealAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_Marca_InatecResult[] DocVenta_ReporteVenta_MarcaInatec(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaInatec(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_Marca_InatecResult[]> DocVenta_ReporteVenta_MarcaInatecAsync(int idEmpresa, int codigoUsuario, string ID_Vendedor, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaInatecAsync(idEmpresa, codigoUsuario, ID_Vendedor, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProducto_InatecResult[] DocVenta_ReporteVenta_MarcaProductoInatec(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaProductoInatec(idEmpresa, codigoUsuario, ID_Marca, ID_Zona, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaProducto_InatecResult[]> DocVenta_ReporteVenta_MarcaProductoInatecAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.Nullable<int> ID_Zona, string ID_Cliente, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaProductoInatecAsync(idEmpresa, codigoUsuario, ID_Marca, ID_Zona, ID_Cliente, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsPresupuesto_ZonaResult[] Presupuesto_Zona(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Presupuesto_Zona(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPresupuesto_ZonaResult[]> Presupuesto_ZonaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Presupuesto_ZonaAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaCliente_InatecResult[] DocVenta_ReporteVenta_MarcaClienteInatec(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaClienteInatec(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaCliente_InatecResult[]> DocVenta_ReporteVenta_MarcaClienteInatecAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaClienteInatecAsync(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedor_InatecResult[] DocVenta_ReporteVenta_MarcaVendedorInatec(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaVendedorInatec(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsDocVenta_ReporteVenta_MarcaVendedor_InatecResult[]> DocVenta_ReporteVenta_MarcaVendedorInatecAsync(int idEmpresa, int codigoUsuario, System.Nullable<int> ID_Marca, System.DateTime fechaInicio, System.DateTime fechaFinal) {
            return base.Channel.DocVenta_ReporteVenta_MarcaVendedorInatecAsync(idEmpresa, codigoUsuario, ID_Marca, fechaInicio, fechaFinal);
        }
        
        public GS.SISGEGS.DM.gsPresupuesto_Reporte_MarcaResult[] Presupuesto_Reporte_Marca(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Presupuesto_Reporte_Marca(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsPresupuesto_Reporte_MarcaResult[]> Presupuesto_Reporte_MarcaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.Presupuesto_Reporte_MarcaAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.gsVentaPronostico_vs_RealResult[] gsVentaPronostico_vs_Real(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.gsVentaPronostico_vs_Real(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.gsVentaPronostico_vs_RealResult[]> gsVentaPronostico_vs_RealAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.gsVentaPronostico_vs_RealAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.ReporteVentas_FamiliaResult[] ReporteVentas_Familia(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_Familia(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_FamiliaResult[]> ReporteVentas_FamiliaAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_FamiliaAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.ReporteVentas_ItemsResult[] ReporteVentas_Items(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_Items(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_ItemsResult[]> ReporteVentas_ItemsAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_ItemsAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.ReporteVentas_ZonasResult[] ReporteVentas_Zonas(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_Zonas(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_ZonasResult[]> ReporteVentas_ZonasAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_ZonasAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.ReportesIntranet_ListarResult[] ReportesIntranet_Lista(int idUsuario) {
            return base.Channel.ReportesIntranet_Lista(idUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ReportesIntranet_ListarResult[]> ReportesIntranet_ListaAsync(int idUsuario) {
            return base.Channel.ReportesIntranet_ListaAsync(idUsuario);
        }
        
        public GS.SISGEGS.DM.PermisosUsuarios_ListarResult[] PermisosUsuarios_ListarResult(int idEmpresa, int codigoUsuario, string texto, int reporte) {
            return base.Channel.PermisosUsuarios_ListarResult(idEmpresa, codigoUsuario, texto, reporte);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.PermisosUsuarios_ListarResult[]> PermisosUsuarios_ListarResultAsync(int idEmpresa, int codigoUsuario, string texto, int reporte) {
            return base.Channel.PermisosUsuarios_ListarResultAsync(idEmpresa, codigoUsuario, texto, reporte);
        }
        
        public GS.SISGEGS.DM.ZonasPermisos_ListarResult[] ZonaPersonal_Listar(int idEmpresa, int codigoUsuario, int id_Permiso) {
            return base.Channel.ZonaPersonal_Listar(idEmpresa, codigoUsuario, id_Permiso);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ZonasPermisos_ListarResult[]> ZonaPersonal_ListarAsync(int idEmpresa, int codigoUsuario, int id_Permiso) {
            return base.Channel.ZonaPersonal_ListarAsync(idEmpresa, codigoUsuario, id_Permiso);
        }
        
        public void Zona_Registrar(int idEmpresa, int codigoUsuario, int idPermiso, int id_zona, int estado) {
            base.Channel.Zona_Registrar(idEmpresa, codigoUsuario, idPermiso, id_zona, estado);
        }
        
        public System.Threading.Tasks.Task Zona_RegistrarAsync(int idEmpresa, int codigoUsuario, int idPermiso, int id_zona, int estado) {
            return base.Channel.Zona_RegistrarAsync(idEmpresa, codigoUsuario, idPermiso, id_zona, estado);
        }
        
        public GS.SISGEGS.DM.Zonas_ReportesResult[] Zonas_Listar(int idEmpresa, int codigoUsuario, int id_zona) {
            return base.Channel.Zonas_Listar(idEmpresa, codigoUsuario, id_zona);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.Zonas_ReportesResult[]> Zonas_ListarAsync(int idEmpresa, int codigoUsuario, int id_zona) {
            return base.Channel.Zonas_ListarAsync(idEmpresa, codigoUsuario, id_zona);
        }
        
        public GS.SISGEGS.DM.UsuarioReporte_ListarResult[] UsuarioReporte_Listar(int idEmpresa, int codigoUsuario, int idUsuario, string texto) {
            return base.Channel.UsuarioReporte_Listar(idEmpresa, codigoUsuario, idUsuario, texto);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.UsuarioReporte_ListarResult[]> UsuarioReporte_ListarAsync(int idEmpresa, int codigoUsuario, int idUsuario, string texto) {
            return base.Channel.UsuarioReporte_ListarAsync(idEmpresa, codigoUsuario, idUsuario, texto);
        }
        
        public GS.SISGEGS.DM.ZonasReporte_ListarResult[] ZonasReporte_Listar(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte) {
            return base.Channel.ZonasReporte_Listar(idEmpresa, codigoUsuario, idUsuario, idReporte);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ZonasReporte_ListarResult[]> ZonasReporte_ListarAsync(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte) {
            return base.Channel.ZonasReporte_ListarAsync(idEmpresa, codigoUsuario, idUsuario, idReporte);
        }
        
        public int PermisosReportes_Registrar(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte, int Activo) {
            return base.Channel.PermisosReportes_Registrar(idEmpresa, codigoUsuario, idUsuario, idReporte, Activo);
        }
        
        public System.Threading.Tasks.Task<int> PermisosReportes_RegistrarAsync(int idEmpresa, int codigoUsuario, int idUsuario, int idReporte, int Activo) {
            return base.Channel.PermisosReportes_RegistrarAsync(idEmpresa, codigoUsuario, idUsuario, idReporte, Activo);
        }
        
        public GS.SISGEGS.DM.ReporteVentas_R3_1Result[] ReporteVentas_R3_1(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_R3_1(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_R3_1Result[]> ReporteVentas_R3_1Async(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, int id_zona, string id_vendedor) {
            return base.Channel.ReporteVentas_R3_1Async(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, id_zona, id_vendedor);
        }
        
        public GS.SISGEGS.DM.ReporteVentas_EstadoResultadosResult[] ReporteVentas_Resultados(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona, string NombreUnidad) {
            return base.Channel.ReporteVentas_Resultados(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, Nombre_Zona, NombreUnidad);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ReporteVentas_EstadoResultadosResult[]> ReporteVentas_ResultadosAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona, string NombreUnidad) {
            return base.Channel.ReporteVentas_ResultadosAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, Nombre_Zona, NombreUnidad);
        }
        
        public GS.SISGEGS.DM.Listar_Zona_BIResult[] Listar_Zona_BI(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona) {
            return base.Channel.Listar_Zona_BI(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, Nombre_Zona);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.Listar_Zona_BIResult[]> Listar_Zona_BIAsync(int idEmpresa, int codigoUsuario, System.DateTime FechaDesde, System.DateTime FechaHasta, string Nombre_Zona) {
            return base.Channel.Listar_Zona_BIAsync(idEmpresa, codigoUsuario, FechaDesde, FechaHasta, Nombre_Zona);
        }
        
        public GS.SISGEGS.DM.Listar_Unidad_BIResult[] Listar_Unidad_BI(int idEmpresa, int codigoUsuario) {
            return base.Channel.Listar_Unidad_BI(idEmpresa, codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.Listar_Unidad_BIResult[]> Listar_Unidad_BIAsync(int idEmpresa, int codigoUsuario) {
            return base.Channel.Listar_Unidad_BIAsync(idEmpresa, codigoUsuario);
        }
    }
}
