//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.SISGEGS.WINServ.MarcasWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarcasWCF.IMarcasWCF")]
    public interface IMarcasWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/TitularMarca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/TitularMarca_ListarResponse")]
        GS.SISGEGS.DM.TitularMarca_ListarResult[] TitularMarca_Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/TitularMarca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/TitularMarca_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.TitularMarca_ListarResult[]> TitularMarca_ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/RegistroMarca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/RegistroMarca_ListarResponse")]
        GS.SISGEGS.DM.RegistroMarca_ListarResult[] RegistroMarca_Listar(int idEmpresa, int idMarca, int idTipo, int idPais, int idTitular, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/RegistroMarca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/RegistroMarca_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.RegistroMarca_ListarResult[]> RegistroMarca_ListarAsync(int idEmpresa, int idMarca, int idTipo, int idPais, int idTitular, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/TipoMarca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/TipoMarca_ListarResponse")]
        GS.SISGEGS.DM.TipoMarca_ListarResult[] TipoMarca_Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/TipoMarca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/TipoMarca_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.TipoMarca_ListarResult[]> TipoMarca_ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/Pais_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/Pais_ListarResponse")]
        GS.SISGEGS.DM.Pais_ListarResult[] Pais_Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/Pais_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/Pais_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.Pais_ListarResult[]> Pais_ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/Marca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/Marca_ListarResponse")]
        GS.SISGEGS.DM.Marca_ListarResult[] Marca_Listar(string nombreMarca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/Marca_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/Marca_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.Marca_ListarResult[]> Marca_ListarAsync(string nombreMarca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/ResponsablesRegistros_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/ResponsablesRegistros_ListarResponse")]
        GS.SISGEGS.DM.ResponsablesRegistros_ListarResult[] ResponsablesRegistros_Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/ResponsablesRegistros_Listar", ReplyAction="http://tempuri.org/IMarcasWCF/ResponsablesRegistros_ListarResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.ResponsablesRegistros_ListarResult[]> ResponsablesRegistros_ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/RegistroMarca_Notificacion", ReplyAction="http://tempuri.org/IMarcasWCF/RegistroMarca_NotificacionResponse")]
        GS.SISGEGS.DM.RegistroMarca_NotificacionResult[] RegistroMarca_Notificacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarcasWCF/RegistroMarca_Notificacion", ReplyAction="http://tempuri.org/IMarcasWCF/RegistroMarca_NotificacionResponse")]
        System.Threading.Tasks.Task<GS.SISGEGS.DM.RegistroMarca_NotificacionResult[]> RegistroMarca_NotificacionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarcasWCFChannel : GS.SISGEGS.WINServ.MarcasWCF.IMarcasWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarcasWCFClient : System.ServiceModel.ClientBase<GS.SISGEGS.WINServ.MarcasWCF.IMarcasWCF>, GS.SISGEGS.WINServ.MarcasWCF.IMarcasWCF {
        
        public MarcasWCFClient() {
        }
        
        public MarcasWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarcasWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarcasWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarcasWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GS.SISGEGS.DM.TitularMarca_ListarResult[] TitularMarca_Listar() {
            return base.Channel.TitularMarca_Listar();
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.TitularMarca_ListarResult[]> TitularMarca_ListarAsync() {
            return base.Channel.TitularMarca_ListarAsync();
        }
        
        public GS.SISGEGS.DM.RegistroMarca_ListarResult[] RegistroMarca_Listar(int idEmpresa, int idMarca, int idTipo, int idPais, int idTitular, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.RegistroMarca_Listar(idEmpresa, idMarca, idTipo, idPais, idTitular, fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.RegistroMarca_ListarResult[]> RegistroMarca_ListarAsync(int idEmpresa, int idMarca, int idTipo, int idPais, int idTitular, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.RegistroMarca_ListarAsync(idEmpresa, idMarca, idTipo, idPais, idTitular, fechaInicio, fechaFin);
        }
        
        public GS.SISGEGS.DM.TipoMarca_ListarResult[] TipoMarca_Listar() {
            return base.Channel.TipoMarca_Listar();
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.TipoMarca_ListarResult[]> TipoMarca_ListarAsync() {
            return base.Channel.TipoMarca_ListarAsync();
        }
        
        public GS.SISGEGS.DM.Pais_ListarResult[] Pais_Listar() {
            return base.Channel.Pais_Listar();
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.Pais_ListarResult[]> Pais_ListarAsync() {
            return base.Channel.Pais_ListarAsync();
        }
        
        public GS.SISGEGS.DM.Marca_ListarResult[] Marca_Listar(string nombreMarca) {
            return base.Channel.Marca_Listar(nombreMarca);
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.Marca_ListarResult[]> Marca_ListarAsync(string nombreMarca) {
            return base.Channel.Marca_ListarAsync(nombreMarca);
        }
        
        public GS.SISGEGS.DM.ResponsablesRegistros_ListarResult[] ResponsablesRegistros_Listar() {
            return base.Channel.ResponsablesRegistros_Listar();
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.ResponsablesRegistros_ListarResult[]> ResponsablesRegistros_ListarAsync() {
            return base.Channel.ResponsablesRegistros_ListarAsync();
        }
        
        public GS.SISGEGS.DM.RegistroMarca_NotificacionResult[] RegistroMarca_Notificacion() {
            return base.Channel.RegistroMarca_Notificacion();
        }
        
        public System.Threading.Tasks.Task<GS.SISGEGS.DM.RegistroMarca_NotificacionResult[]> RegistroMarca_NotificacionAsync() {
            return base.Channel.RegistroMarca_NotificacionAsync();
        }
    }
}
